### ISSUE TITLE
Can't run it. Device 'd:' not found

### ISSUE THREAD

**Issue by ewoks** [Genymobile/gnirehtet#1]
// I wrote following line in terminal, next 3 lines are output written by ghirehtet:
./gnirehtet rt
Starting gnirehtet...
'adb' -s 'd:' reverse tcp:31416 tcp:31416
error: device 'd:' not found
// Dialog should appear but it doesn't 

Siera macOS 10.12.4,
adb 1.0.39
Android 5.0.1, Samsung (I know, I am sorry) 

// If I manually install, than execute:
adb reverse tcp:31416 tcp:31416
adb shell am startservice -a com.genymobile.gnirehtet.START
// => Dialog appears as expected

**Comment by rom1v** [comment]
It seems that you executed the command with an additional argument having value `d:`:

    ./gnirehtet rt d:

Did you do that?

**Comment by ewoks** [comment]
not really, that is why I am surprised as well where 'd:' is coming from

**Comment by ewoks** [comment]
Tested with other non Samsung device (N5): Same error

**Comment by rom1v** [comment]
Commit ee407b9e44fa907eb7f964b71f021255f853affd should fix the issue.

**Comment by ewoks** [comment]
I can confirm that problem is not there anymore on macOS and stdout is showing:
2017-03-31 13:15:36.122 I Main: Starting server...
ticket can be closed and new script packed in the latest release ;) thanks

**Comment by rom1v** [comment]
:+1:
