### ISSUE TITLE
Upgrade to 2.2 how to 

### ISSUE THREAD

**Issue by LrGit** [Genymobile/gnirehtet#100]
Hi. I use your previous version (rust) which I find particularly usefull on home pc and when travelling with a laptop - both use Win 10. I am not familiar with either linux or rust but must have a bit of knowledge in order to get it working.  Hope it's ok to post my question here as it's the only place I could find to contact you easily

How do I upgrade from the previous version to 2.2 please?. Is there an easy way?

You have done a great job with this. But I imagine far more people would use it had an easier install method

**Comment by rom1v** [comment]
Since there is no installation, just download the new version and execute it instead of the old one.

**Comment by LrGit** [comment]
Most cool. Might have helped if I had downed the correct version :)

Also had problems with windows deciding I was not allowed to remove the old folder so looked for services etc. Solved by moving all files to a new folder 

For others:
1. Uninstall old version of gnirehtet from phone
2. Restart phone
3. Copy apk to phone and then install it
4. Run 'gnirehtet-run.cmd'
5. Smile

Thanks for the help

**Comment by rom1v** [comment]
Steps 1, 2 and 3 should not be necessary.

**Comment by LrGit** [comment]
OK. But for my info -why not?

**Comment by rom1v** [comment]
On gnirehtet start, it checks the version installed on the device. If the version does not match, it installs the new one.

**Comment by LrGit** [comment]
Most cool
