### ISSUE TITLE
Some apps don't work? 

### ISSUE THREAD

**Issue by p2635** [Genymobile/gnirehtet#101]
It's my first time usig gnirehtet and it works pretty nicely, thanks for your hard work. However, I noticed some apps don't work but I don't know why. For example YouTube.

Device: Samsung S6
gnirehtet-rust-linux64-v2.2.1.zip

Let me know if more info is needed.

**Comment by rom1v** [comment]
Some apps check whether wifi or mobile network is available, and they consider that there is no connection with reverse tethering. See https://github.com/Genymobile/gnirehtet/issues/37.

**Comment by p2635** [comment]
@rom1v thanks Romain, I didn't see that, you can close it. I guess there's no way around it.
