### ISSUE TITLE
no ring notification for google voice calls routed to the hangouts app

### ISSUE THREAD

**Issue by bughit** [Genymobile/gnirehtet#103]
stock android 8.1

hangouts can receive google voice calls over ip

works fine over wifi or cell data, but not gnirehtet (but the way, why not a shorter rehtet)

calling from hangouts works fine

**Comment by rom1v** [comment]
Probably related to https://github.com/Genymobile/gnirehtet/issues/101.

If your device is connected to wifi, does it work through gnirehtet (wifi will be connected, but not used)?

**Comment by bughit** [comment]
Sorry the problem was not specific gnirehet, it was the phone that was ringing which I thought I turned off in google voice, and hangouts was not ringing on any network. Clearing hangouts and hangouts dialer cache and data and reinstalling them resolved this.
