### ISSUE TITLE
Should it be disconnecting from the relay server and not reconnecting on its own when ...

### ISSUE THREAD

**Issue by bughit** [Genymobile/gnirehtet#104]
1. you switch usb mode from charging to file transfer?
2. disconnect and reconnect the usb cable?

it seems like it should be possible to reconnect since the app and the server are both still running

**Comment by rom1v** [comment]
See https://github.com/Genymobile/gnirehtet/issues/47#issuecomment-335411761.

Calling `./gnirehtet tunnel` restart the tunnel so that the client and server may reach each other.

Otherwise, use `./gnirehtet autostart` to start whenever a device is connected.
