### ISSUE TITLE
Google Play can't download apps

### ISSUE THREAD

**Issue by akirayamamoto** [Genymobile/gnirehtet#106]
This software works well for Whatsapp and Google Chrome but Google Play doesn't identify a connection and keep waiting. I would like to use reverse tethering to avoid data costs while installing apps. Google Photos also keeps waiting for a connection. Other than that gnirehtet works good.

Tks

**Comment by rom1v** [comment]
Thank you for your report.

This is a duplicate of https://github.com/Genymobile/gnirehtet/issues/37.
