### ISSUE TITLE
Previous VPN settings suggestion

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#11]
The previous VPN should be disabled when the client is started and enabled when the client is stopped.

**Comment by ewoks** [comment]
Needs more description. It is not clear what is the actual issue.

**Comment by Zero3K** [comment]
I am using Blokada on my device. It uses a local VPN connection to filter ads. The VPN it made should be automatically switched on/off so that way it will work when the tethering is stopped.

**Comment by rom1v** [comment]
The VPN management is done by the Android system, we won't try to override it (the behavior may be different on several Android versions).
