### ISSUE TITLE
Local dns resolution is not working

### ISSUE THREAD

**Issue by varundtsfi** [Genymobile/gnirehtet#114]
I have tried this working well on my system but my local sites i am not able to open through this.
Global website's or link's are opening using internet but local dns resolution is not happening.
on my local network my site varun-pc.dumps.com is not working.
If i have to do the same, how to do that..please help 

Thanks a lot for this utility.
Thanks in advance I am waiting for you sincere reply.

**Comment by rom1v** [comment]
Pass your DNS as a parameter:

    gnirehtet run -d 1.2.3.4

If your DNS is localhost (127.0.0.1) on the desktop, use the special mapping 10.0.2.2:

    gnirehtet run -d 10.0.2.2

**Comment by varundtsfi** [comment]
@rom1v  Thank you so much Its working now. I want to study this code for my project so from where I can start as I am new in android, and network stuff in java.

**Comment by rom1v** [comment]
> from where I can start

https://github.com/Genymobile/gnirehtet/blob/master/DEVELOP.md
