### ISSUE TITLE
Suggestion for a service to turn off when its in use

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#12]
It should turn off the Wifi connection when the client is started and turn it back on when the client is stopped.

**Comment by Zero3K** [comment]
Actually, it'll be better to make a fake Wifi connection so that way programs that don't work without Wifi will work when its running.

**Comment by ewoks** [comment]
Too much work for few sparkles and shiny things. Unnecessary in my opinion.

**Comment by Zero3K** [comment]
The fake Wifi would get Netflix, etc. to work with it.

**Comment by rom1v** [comment]
IMO, _gnirehtet_ should not change various system settings based on what it guesses the user would like, it would never get it right.

For example, reverse tethering is implemented over _adb_, which may run over USB or over wifi. What if we start _gnirehtet_ when _adb_ is over wifi (this could be useful to use it as a "SOCKS-like" server)?

Also, if you use a device with API > 22, apps should be aware that a network is available (except if they explicitly check for wifi, but in that case, the user may enable wifi manually).
