### ISSUE TITLE
GnirehtetControlReceiver: requires android.permission.WRITE_SECURE_SETTINGS

### ISSUE THREAD

**Issue by eku** [Genymobile/gnirehtet#120]
Starting the Android part results in the following error:

```
06-21 08:54:26.746  1676  1703 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.genymobile.gnirehtet.START flg=0x10 cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver } from null (pid=18329, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS due to receiver com.genymobile.gnirehtet/.GnirehtetControlReceiver
```

In the App permission settings there is no option to enable this permission.

Phone: _Android 7.1.2, Xiaomi Mi Max 2_

**Comment by rom1v** [comment]
See https://github.com/Genymobile/gnirehtet/issues/5#issuecomment-297045539

**Comment by eku** [comment]
@rom1v  No, that doesn't help with MIUI 9.

**Comment by rom1v** [comment]
Then https://github.com/Genymobile/gnirehtet/issues/40#issuecomment-328364663.

**Comment by wahdatjan** [comment]
In mi phones go to developer options > Allow USB debugging(Security settings)
