### ISSUE TITLE
Changing routes while relay server is running

### ISSUE THREAD

**Issue by jo215** [Genymobile/gnirehtet#123]
Hi,
Thanks for the great project. Looking through the code (I am no rust expert) it seems that the client should be able to be stopped and then restarted with different routes/dns servers without restarting the relay? 

However I have been unable to get this to work even after restarting the tunnel. Is this something that should work out of the box or do I need to restart the relay each time a route/dns server address changes?

**Comment by rom1v** [comment]
> it seems that the client should be able to be stopped and then restarted with different routes/dns servers without restarting the relay?
Correct. They are [client-side](https://github.com/Genymobile/gnirehtet/blob/v2.2.1/app/src/main/java/com/genymobile/gnirehtet/GnirehtetService.java#L114-L132) settings.

If you stop, then start, it should work without restarting the relay server.

**Comment by jo215** [comment]
Ah, looks like a problem with my dns. Thanks for the quick answer.
