### ISSUE TITLE
Problem with Wifi tethering

### ISSUE THREAD

**Issue by sianhulo** [Genymobile/gnirehtet#126]
So I attempted to create a wifi network with the phone that is connected to gnirehtet, the phone in question successfully gets internet, but the devices connected to it by wifi don't. Every time something attempts to be loaded from one of the connected devices, gnirehtet will print the following in console:
`WARN Router: Dropping invalid packet`
The phone in question uses android oreo 8.1.
So, Computer -> Phone works fine, but Computer -> Phone -> Devices doesn't.

I'm using the rust version, and linux (kernel version 4.17) if it matters.

Edit: Tried with another phone as "gateway", this one with android 5.1, and the results are the same. Android 5.1 gets internet from gnirehtet but the devices connect to the phone through wifi tether don't. I get the same warning.

**Comment by rom1v** [comment]
> So I attempted to create a wifi network with the phone that is connected to gnirehtet, the phone in question successfully gets internet, but the devices connected to it by wifi don't.

Yes, this is "expected" (it does not work for me either).

**Comment by SanujBansal** [comment]
I am also trying the same as it is India vs newzealand cricket semi final today @sianhulo but it does not work.

**Comment by gypdo** [comment]
Did u get any solution? Cuz it'd be very usefull for me

**Comment by rom1v** [comment]
No, I don't have a solution.

**Comment by gypdo** [comment]
Do u have some idea what is the problem?

**Comment by ThibaultLemaire** [comment]
Why was this issue closed? There is a usecase for wifi tethering with gnirehtet

**Comment by rom1v** [comment]
Because apparently Android does not support both wifi hotspot and VpnService simultaneously. AFAIK there's nothing we can do.
