### ISSUE TITLE
GRPC

### ISSUE THREAD

**Issue by jo215** [Genymobile/gnirehtet#127]
I am trying to communicate with a GRPC service via gnirehtet. GRPC seems to run over TCP, but I am not seeing any traffic over the tunnel.
Do you have any ideas as to what the problem may be?

**Comment by rom1v** [comment]
Does gnirehtet work as expected otherwise (browsing website, etc.)?

**Comment by jo215** [comment]
Yes, fine. However, some further testing is showing my grpc client (android side ) fails to talk to the server even when I exclude the server's address from the routes I supply to gnirehtet (and keep wifi on). It works fine if gnirehtet is not working.... It could be problems with my client app I guess...

**Comment by rom1v** [comment]
Could you provide concrete examples, please? (ip of the server, the parameters you pass to exclude routes, any relevant logs in `adb logcat` or in gnirehtet output...)

**Comment by jo215** [comment]
Hey, thanks for getting back to me. It turned out that the grpc client on the device was waiting for the network to come up, and not detecting the vpn. I added some code to detect the case when the vpn is connected, and all works as expected. Case closed!
