### ISSUE TITLE
Internet not working and "WARN Router: Dropping invalid packet" on Moto G4 with LineageOS 15.1 / Ubuntu 16.04

### ISSUE THREAD

**Issue by mensch72** [Genymobile/gnirehtet#137]
Having installed and started gnirehtet rust as in the readme, the Moto G4 shows the notification that reverse tethering is enables, but the phone still has no internet connection (mobile data and Wifi are turned off, device is not rooted). 

When trying `ping 4.2.2.1` via `adb shell`, the gnirehtet log only says 
`WARN Router: Dropping invalid packet`. 

When trying to ping a URL, it gets not even resolved and the log repeatedly shows somthing like:
`2018-08-23 10:42:59.564 INFO UdpConnection: 10.0.0.2:17767 -> 8.8.8.8:53 Open`
`2018-08-23 10:42:59.565 INFO UdpConnection: 10.0.0.2:17767 -> 8.8.8.8:53 Close`

**Comment by mensch72** [comment]
solved. I had to tell gnirehtet my DNS manually, in my case
`./gnirehtet run -d 192.168.2.1`
ping still gave the same warning, but internet worked anyway.

**Comment by rom1v** [comment]
:+1:

> ping still gave the same warning

This is expected, _gnirehtet_ only forwards TCP and UDP (ping is ICMP).
