### ISSUE TITLE
sockets 'connect' when IP address unreachable

### ISSUE THREAD

**Issue by jo215** [Genymobile/gnirehtet#147]
Hi there,

After setting up specific routes, I would like to test if I can connect to them OK. I am using socket.connect() from the client side, but this will successfully return even if I pull the network cable from the (linux/rust) relay server.

Is this an artifact of how the (non-blocking) relay server works, or do you think this is a bug?

Regards,

James

**Comment by rom1v** [comment]
> Is this an artifact of how the (non-blocking) relay server works, or do you think this is a bug?

Gnirehtet [sends](https://github.com/Genymobile/gnirehtet/blob/v2.3/relay-rust/src/relay/tcp_connection.rs#L228) the [SYN+ACK](https://github.com/Genymobile/gnirehtet/blob/v2.3/relay-rust/src/relay/tcp_connection.rs#L379) to the client only when the "real" `connect()` succeeds.

But the connection passes through the `adb reverse` tunnel, which will make `connect()` succeed whenever the tunnel is active. It would be the same with an SSH tunnel.

I also had this problem in gnirehtet itself (inception): https://github.com/Genymobile/gnirehtet/commit/47fae70ec0e85adf9753ee617a261a026c272aa3.

You need a read or write to detect connection failure.

**Comment by jo215** [comment]
OK, that makes sense.
Thankyou.

/James

**Comment by jo215** [comment]
Hey, I have tested this and results are as expected. Thanks for the explanation - closing issue.
