### ISSUE TITLE
Issue with using Pi-hole as its custom DNS

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#15]
Some ads aren't being blocked when using a Raspberry Pi that has Pi-hole running as the custom DNS. I added the lists that are in the app (which is called Blokada) that I am using on the tablet (which does block the problematic ads) but they are still showing up every so often in the "Free Video chat online" app (NSFW).

**Comment by rom1v** [comment]
> Some ads aren't being blocked when using a Raspberry Pi that has Pi-hole running as the custom DNS

Is it relayed to _gnirehtet_?

**Comment by Zero3K** [comment]
I did some testing. It turns out to be a problem with gnirehtet since the ads are blocked after adding the blocklists I was using in Blokada to the Pi-hole and dissbling Blokada (thereby using only the Pi-hole to block ads).

**Comment by rom1v** [comment]
I don't really know all the tools you are talking about, but _gnirehtet_ [just use](https://github.com/Genymobile/gnirehtet/blob/90882a5aec291648177cc1e09b252d7a03710930/app/src/main/java/com/genymobile/gnirehtet/GnirehtetService.java#L100-L108) the DNS servers you provide. It is not aware of any blocking-ad related stuff.

**Comment by Zero3K** [comment]
I know. I used the IP of the Pi-hole as the custom DNS server. It seems like not all DNS queries are using it. Otherwise, those ads would have been blocked.

**Comment by Zero3K** [comment]
So, it seems like it should be fixable.

**Comment by rom1v** [comment]
Maybe your Android device already resolved this address and cached it, so that it did not requested it again to the DNS server when you loaded the page.

Otherwise, you can check the UDP connections in the logs (compile the last version though, the last release does not [log](https://github.com/Genymobile/gnirehtet/commit/2ee5367dc311fdcb6c4ae4e7d4a6a3aae6a6e58e) correctly UDP requests), they are probably DNS requests. This may help to follow DNS requests.

For further investigation, you could increase the [https://github.com/Genymobile/gnirehtet/blob/90882a5aec291648177cc1e09b252d7a03710930/relay/src/main/java/com/genymobile/relay/Log.java#L40][log level] to _verbose_ to print the packets data.

**Comment by Zero3K** [comment]
I tried fixing it by using two entries of the same IP in the command line parameter for the relay.jar. It didn't help in fixing it. Now to try increasing the log level to VERBOSE.

**Comment by Zero3K** [comment]
I upgraded to the latest build. Now the custom DNS parameter is no longer working.

**Comment by rom1v** [comment]
> I upgraded to the latest build. Now the custom DNS parameter is no longer working.

Please give more details. I just try it again, it works here.

**Comment by Zero3K** [comment]
I am trying the command via Windows. The command line I am using is "C:\Program Files\Java\jre1.8.0_112\bin\java.exe" -Xms200M -Xmx200M -jar relay.jar  --esa dnsServers 10.0.1.85 > gnirehtet.log.

**Comment by rom1v** [comment]
> The command line I am using is "C:\Program Files\Java\jre1.8.0_112\bin\java.exe" -Xms200M -Xmx200M -jar relay.jar --esa dnsServers 10.0.1.85 > gnirehtet.log.

The DNS servers must be configured on the client-side, so:

    adb shell am startservice -a com.genymobile.gnirehtet.START --esa dnsServers 10.0.1.85

The relay server does not accept any parameters (it ignores them).

**Comment by Zero3K** [comment]
Heh, it was that easy after all. Thanks for telling me how to get it to work.

**Comment by rom1v** [comment]
Was this the root cause of this issue?

**Comment by Zero3K** [comment]
Yes. Now to figure out the issue with the never-ending loading circle, etc.

**Comment by Zero3K** [comment]
So can you figure that out or not?

**Comment by rom1v** [comment]
> So can you figure that out or not?

You mean, the reason why you have an infinite progress bar on your application I know nothing about? No, I can't figure that out ;-)

**Comment by Zero3K** [comment]
Well, you could try it out and see what happens.

**Comment by Zero3K** [comment]
Maybe the app I mentioned is having the same issue as the ones I made issues about. I'll go ahead and close this one since the main reason for it has been figured out. Hopefully the app works when the other ones work properly.

**Comment by Zero3K** [comment]
I am attaching a log with its level set to debug to see if that helps fix the issue with the app I mentioned.

[gnirehtet log.zip](https://github.com/Genymobile/gnirehtet/files/923719/gnirehtet.log.zip)

**Comment by rom1v** [comment]
I have no idea how to correlate what you observe (an infinite progress bar, when?) and 20 minutes of logs.

I can only see that sometimes, for some reasons, Android is trying to connect to the same IP as your DNS server (10.0.1.85) on port 443, but the connection fails. It works only on port 53 (DNS requests) and port 80 (you have probably an HTTP server there).

**Comment by Zero3K** [comment]
1. When viewing the user list after backing out of a chat (Its random though).
2. Yes, Pi-Hole is a Web Server (to show the Web GUI) and a DNS Server. I agree that the port 443 connection is odd.

**Comment by Zero3K** [comment]
2. Like I wrote in another issue, the connections to port 443 of the custom DNS are because it is redirecting the ads which are displayed via HTTPS to itself in order to block them.

**Comment by Zero3K** [comment]
Oh, maybe it doesn't handle timeouts that well. So, it keeps trying to connect with no success.

**Comment by Zero3K** [comment]
Is that an actual problem or not?

**Comment by rom1v** [comment]
I don't think so. I have no concrete element indicating that gnirehtet causes a problem here.
