### ISSUE TITLE
No access to local network

### ISSUE THREAD

**Issue by MCMic** [Genymobile/gnirehtet#152]
My computer is in a part of my house where the wifi is too weak.

So I use gnirehtet to share the ethernet connexion of my computer with my phone.
It works great to access internet, but my phone has no access to the local network.

This may be on purpose, or forced by how tethering works, but would it be possible to at least make sure the computer running gnirehtet is available from the phone so that KDE connect can find it?

**Comment by rom1v** [comment]
The phone should have access to the local network, as seen by the computer which provides the connection. For example, if 192.168.0.5 is reachable from your computer, then it should be reachable from your phone.

(And to access 127.0.0.1 on the host computer, use 10.0.2.2 from the phone.)

**Comment by MCMic** [comment]
From the terminal on the phone in root, I cannot ping neither 10.0.2.2 or 192.168.1.1.

Pinging 192.168.1.1 from the computer works fine.

**Comment by rom1v** [comment]
> From the terminal on the phone in root, I cannot ping neither 10.0.2.2 or 192.168.1.1.

You cannot ping at all. It can only forward TCP and UDP, not ICMP.
But the IP is reachable.

**Comment by MCMic** [comment]
Oh, that makes it hard to check.

Any idea why KDE connect does not see my computer? It works when I’m on the wifi.

**Comment by MCMic** [comment]
J’ai essayé d’ajouter manuellement 10.0.2.2 dans les IPs à tester pour KDE connect mais ça semble pas fonctionner (pourtant je suis tombé sur https://mail.kde.org/pipermail/kdeconnect/2016-April/001481.html )

**Comment by MCMic** [comment]
If I search devices from the computer, it gets weird.
I see my phone listed, but if I try to pair with it, I get the request on the computer, and it seems to pair with itself.
Is there anything in the way IPs are routed that would cause this situation where my computer confuses my phone with itself?

**Comment by rom1v** [comment]
> Is there anything in the way IPs are routed that would cause this situation where my computer confuses my phone with itself?

Yes, your device is not on the local network, every connections are initiated from the computer. It's like connecting to a server while you are behind a NAT, the server will see your public IP, your private IP is not reachable. Here, the NAT is your computer, your device has no IP on the local network.

**Comment by MCMic** [comment]
So my device can see the local network but the opposite is not true?

**Comment by rom1v** [comment]
> So my device can see the local network but the opposite is not true?

Correct.

Only connections initiated by the device to the network are possible (but of course, once they are initiated, communication is bidirectional).

**Comment by MCMic** [comment]
Ok I guess this is where the problem comes from.
I’ll wait to see if KDE connect does not add real USB support instead I guess.

Thanks for all the explanations (and for the software of course)
