### ISSUE TITLE
reverse tethering working only with jumpgo browser if i add proxy & port 8080 other android application are not working any alternative method   

### ISSUE THREAD

**Issue by raafeeq** [Genymobile/gnirehtet#167]

**Comment by rom1v** [comment]
If your internet access requires a HTTP proxy, then you need to configure every client application to use this proxy.

See https://github.com/Genymobile/gnirehtet/issues/4#issuecomment-292917846.

**Comment by raafeeq** [comment]
Please check the blow commands are correct 
adb shell settings put global 10.1.30.10 abc
adb shell settings put global 8080 123

adb shell settings delete global 10.1.30.10
adb shell settings delete global 8080

if i want to use another internet connection. do i need to delete the settings every time ?

**Comment by rom1v** [comment]
> Please check the blow commands are correct
> adb shell settings put global 10.1.30.10 abc
> adb shell settings put global 8080 123

They are not.

    adb shell settings put global global_http_proxy_host 10.1.30.10
    adb shell settings put global global_http_proxy_port 123

> if i want to use another internet connection. do i need to delete the settings every time ?

I think so.

**Comment by raafeeq** [comment]
please check the below commands i am little confuse with it if it is correct or no
adb shell settings put global global_http_proxy_port 8080
adb shell settings delete global global_http_proxy_host 10.1.30.10 
adb shell settings delete global global_http_proxy_port 8080

and what will be the command for one short "adb shell settings put global http_proxy abc:123 # in one shot"
thank you very much

**Comment by rom1v** [comment]
From examples in https://github.com/Genymobile/gnirehtet/issues/4#issuecomment-292917846, replace `abc` by `10.1.30.10` and `123` by `8080`.

**Comment by raafeeq** [comment]
while deleting it shows "too many arguments"

>adb shell settings delete global http_proxy 10.1.30.10:8080
Too many arguments

**Comment by rom1v** [comment]
> while deleting it shows "too many arguments"

Of course, you passed too many arguments.

    adb shell settings delete global http_proxy

**Comment by raafeeq** [comment]
so what will be the correct command to delete "adb shell settings put global http_proxy 10.1.30.10:8080"

**Comment by rom1v** [comment]
Yes, the `put` command sets `http_proxy` to `10.1.30.10:8080`, the `delete` command unsets `http_proxy`.

**Comment by raafeeq** [comment]
now every this working except WhatsApp and IMO is there any alternative way to run these applications.

**Comment by rom1v** [comment]
Because WhatsApp probably does not respect global HTTP proxy settings, or does not use HTTP at all. Or maybe you can configure a specific proxy in WhatsApp settings?

Otherwise, you should use it in a non-filtered network (which does not require a proxy).

**Comment by raafeeq** [comment]
Thank you
