### ISSUE TITLE
Screen turns off & connection disconnects

### ISSUE THREAD

**Issue by mydroidbdkst** [Genymobile/gnirehtet#17]
On my HUAWEI honor 6X, the connection gets disconnected whenever the phones display goes to sleep

**Comment by Zero3K** [comment]
How did you manage to fix it?

**Comment by mydroidbdkst** [comment]
It was HUAWEI  EMUI's battery optimization settings that was killing Gnirehtet, so to fix the problem   I put  Gnirehtet in Protected app list & enabled Gnirehtet to ignore battery optimize settings then everything become normal.
