### ISSUE TITLE
cannot start client: command adb

### ISSUE THREAD

**Issue by idmvrk** [Genymobile/gnirehtet#171]
This is what happens when i start the run file, i have adb properly set up,  when i type adb  into cmd i get a  wall of text with all the options and stuff so im not sure whats the problem? i have debugging mode ON on the phone, cable  connected. (windows7) using RUST version.

`adb --version` says:

    android debug bridge version 1.0.40
    version 4986621
    installed as C:\program files\android\platform-tools\adb.exe

![untitled](https://user-images.githubusercontent.com/34138737/52653887-926f1a80-2ef9-11e9-91c9-c847598f307a.png)

    2019-02-12 19:05:27.558 ERROR Main: Cannot start client: Command adb ["shell", "dumpsys", "package", "com.genymobile.gnirehtet"] returned with value 1

**Comment by rom1v** [comment]
What is the result of:

    adb shell dumpsys package com.genymobile.gnirehtet

?

**Comment by idmvrk** [comment]
> What is the result of:
> 
> ```
> adb shell dumpsys package com.genymobile.gnirehtet
> ```
> ?

welp dunno what  to say but it seems to be working now after i installed huawei "HiSuite" and it seems liek it properly installed my  phone drivers or something so now its recognized and it works lol.... Youtube works, chrome works, sadly i cant download from playstore i guess thats known issue? i  heard about playstore detecting "fake" connections or something?

**Comment by rom1v** [comment]
> sadly i cant download from playstore i guess thats known issue?

See https://github.com/Genymobile/gnirehtet/issues/37.
