### ISSUE TITLE
Help with auto connect

### ISSUE THREAD

**Issue by aldrin0987** [Genymobile/gnirehtet#174]
i currently have this (old version) got from other site 
![Untitled](https://user-images.githubusercontent.com/29282082/54694152-b52cc880-4b62-11e9-9aa8-a3a00c52b43d.png)

and i research if have new version with auto reconnect until i see this 

i download the zip files but i dont know what to do next
Sorry im not a programmer but i want to use this very usefull apps
can anyone give me this with auto reconnect feature like the picture above by clicking the gnirehtet-run.cmd
or step by step process after i download the zip files...  
Thanks ..

**Comment by rom1v** [comment]
Open `cmd.exe` in Windows, then go to the gnirehtet directory using `cd`, then `gnirehtet autorun`.

Alternatively, edit (or copy) `gnirehtet-run.cmd` and replace `gnirehtet.exe run` by `gnirehtet.exe autorun`.

**Comment by aldrin0987** [comment]
sir this the zip i download
![1](https://user-images.githubusercontent.com/29282082/54695943-dd69f680-4b65-11e9-9fe7-3f5b8deea28f.png)

how can i make gnirehtet.exe??

**Comment by rom1v** [comment]
You downloaded the sources. If you want the binary, download the binary: https://github.com/Genymobile/gnirehtet/blob/master/README.md#rust

**Comment by aldrin0987** [comment]
java or rust?

**Comment by aldrin0987** [comment]
thank you very much sir ...
i download the rust version and do the edit autorun and install the new apk .. thank you very much sir...
