### ISSUE TITLE
Dropping ping packet with error `Unsupported IPv4 headers`

### ISSUE THREAD

**Issue by ohenak** [Genymobile/gnirehtet#175]
I am trying to `ping` google.com to make sure the connection is establish. However, in my environment, I am getting this log:
```
2019-03-20 09:06:05.921 D IPv4Packet: Unsupported IPv4 headers
2019-03-20 09:06:05.921 W Router: Dropping invalid packet
```

How can I debug further to understand which header is not supported?

The command that I ran:
`adb shell ping -c 4 google.com`

**Comment by rom1v** [comment]
That's expected. Only TCP and UDP are forwarded, ICMP (ping) is not.
