### ISSUE TITLE
Issue with Netflix

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#18]
When reverse tethering via gnirehtet, Netflix takes longer to load when ran.

**Comment by rom1v** [comment]
Same as https://github.com/Genymobile/gnirehtet/issues/19?

**Comment by Zero3K** [comment]
Nope. This issue is different than that one.

**Comment by Zero3K** [comment]
Any news regarding this issue?

**Comment by Zero3K** [comment]
Its probably an issue with how it handles the connections the device makes.

**Comment by Zero3K** [comment]
I guess its not fixable then?

**Comment by rom1v** [comment]
Yes, without more specific information, this is not really a bug.

**Comment by Zero3K** [comment]
How do I give you more specific information?

**Comment by rom1v** [comment]
I don't know, but "Netflix takes longer to load" when using one network (communicating over _adb_) instead of another is not a bug in itself… There is nothing specific to fix.

**Comment by Zero3K** [comment]
The speed of the network hasn't changed though. In fact, the connecting to its servers should be quicker since there isn't as much latency.

**Comment by Zero3K** [comment]
Now it cannot even connect to its servers. I am attaching a log that has its level set to debug.

[gnirehtet log.zip](https://github.com/Genymobile/gnirehtet/files/923694/gnirehtet.log.zip)

**Comment by rom1v** [comment]
Same as your other logs, all the connections to `10.0.1.85:443` fail.

**Comment by Zero3K** [comment]
Oh, that's because its the Pi-Hole is redirecting HTTPS based ads to its IP so they are blocked from showing.
