### ISSUE TITLE
No connection request confirmation

### ISSUE THREAD

**Issue by eeke1** [Genymobile/gnirehtet#180]
gnirehtet gives a broadcast completed with a result = 0 .

USB debugging is on and the phone confirms that.

No broadcast request occurs though, attached is a log.
[logacat.txt](https://github.com/Genymobile/gnirehtet/files/3026263/logacat.txt)

**Comment by rom1v** [comment]
Some devices require to "authorize" the app manually, but each in different ways.

See for instance https://github.com/Genymobile/gnirehtet/issues/150#issuecomment-440989256 or https://github.com/Genymobile/gnirehtet/issues/161#issuecomment-455324982.

**Comment by eeke1** [comment]
I have a huawei vtr-al00 and was hoping that placing it manually ala [#161 (comment)](https://github.com/Genymobile/gnirehtet/issues/161#issuecomment-455324982) would do the trick.

It didn't, and most frustratingly I can't tell if the app is running in background since I have no recent apps button.

**Comment by rom1v** [comment]
Should be fixed by f8681809a28a0073f791f0d9eae65da02ae73c3d.
