### ISSUE TITLE
Command adb returned with value 1

### ISSUE THREAD

**Issue by Srikanth9142** [Genymobile/gnirehtet#186]
2019-04-13 08:23:05.884 INFO Main: Starting relay server...
2019-04-13 08:23:05.884 INFO Main: Checking gnirehtet client...
2019-04-13 08:23:05.884 INFO Relay: Relay server started
2019-04-13 08:23:05.899 ERROR Main: Cannot start client: Command adb ["shell", "dumpsys", "package", "com.genymobile.gnirehtet"] returned with value 1

**Comment by rom1v** [comment]
Your device is not detected by `adb`.

Did you enable USB Debugging? On Windows, you may need some [drivers](https://developer.android.com/studio/run/oem-usb.html).

You can check it works by executing `adb devices`.

**Comment by Srikanth9142** [comment]
Yes, USB debugging enabled.Didn't have drivers i think

**Comment by JohnSt99** [comment]
If you are running bluestacks also make sure to specify which device 

- Use `adb devices` to find your device id
- use the `gnirehtet run <device_id>` command instead

**Comment by evilnero** [comment]
Try closing or stopping the adb.exe process in Task Manager — it helped in my case.
Sometimes adb.exe remains running in the background for no apparent reason, possibly from a previous session. After ending it manually, the client started correctly.

I edited gnirehtet-run.cmd file:

gnirehtet.exe run
taskkill /IM gnirehtet.exe /F
taskkill /IM adb.exe /F
pause

And don't hit Y when stopping it with CTRL+C, answer N.
