### ISSUE TITLE
Broadcast completed: result=0

### ISSUE THREAD

**Issue by HarEka** [Genymobile/gnirehtet#187]
Checked throught previous threads and couldn't solve it.

Phone Huawei P30 Pro
Operating system EMUI 9.0

Error: Broadcasting: Intent { act=com.genymobile.gnirehtet.START flg=0x400000 cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver }
Broadcast completed: result=0

**Comment by HarEka** [comment]
Got this when i used ./adb logcat

![bild](https://user-images.githubusercontent.com/49623188/56099635-db4e4a00-5f0f-11e9-8990-d4af779ff356.png)

**Comment by HarEka** [comment]
![bild](https://user-images.githubusercontent.com/49623188/56141715-a2f54d00-5f9d-11e9-80f6-7ddc5266079d.png)

**Comment by HarEka** [comment]
![bild](https://user-images.githubusercontent.com/49623188/56142100-5eb67c80-5f9e-11e9-8103-defd77f0dcd9.png)

**Comment by HarEka** [comment]
I got it to work now. But does anyknow know if it is possible to create a hotspot from my phone using the network from my pc?

**Comment by HarEka** [comment]
how do i change the vpns dns server?

**Comment by rom1v** [comment]
> But does anyknow know if it is possible to create a hotspot from my phone using the network from my pc?

Not possible with gnirehtet (at least, I never figured out how).

> how do i change the vpns dns server?

```
./gnirehtet run -d xx.xx.xx.xx
```

**Comment by ben-mathu** [comment]
> I got it to work now. But does anyknow know if it is possible to create a hotspot from my phone using the network from my pc?

How did you do this, i have the same problem.

**Comment by rom1v** [comment]
Should be fixed by f8681809a28a0073f791f0d9eae65da02ae73c3d.
