### ISSUE TITLE
Issue with DirecTV

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#19]
When watching a recording stored on the DVR, the quality is bad and there's lots of buffering occurring.

**Comment by rom1v** [comment]
I did some quick [tests](http://blog.rom1v.com/2017/03/gnirehtet/#comment-3) (in French) recently to compare the performances with that of `adb push`.

It appears that the bitrate is similar to what `adb push` provides: ~5MB/s (40Mbps) on a Nexus 5 with Android 6.

What's the bitrate of your video? What if you do the same test from your computer directly?

**Comment by Zero3K** [comment]
I don't know what that has to do with it. Netflix will work fine on my PC since my Internet is fast enough.

**Comment by rom1v** [comment]
> I don't know what that has to do with it. Netflix will work fine on my PC since my Internet is fast enough.

_Gnirehtet_ client and relay server communicate over _adb_, so it may not be faster that what _adb_ provides…

**Comment by Zero3K** [comment]
Its probably an issue with how it handles the connections the device makes.

**Comment by ewoks** [comment]
Of course communication thought adb can not be faster than adb allows.
@Zero3K "probably" doesn't help here at all. Can you pin point to specific place where handling connection is wrong?

**Comment by Zero3K** [comment]
I don't know. I thought you all would test the mentioned app to figure out if it really is having the issue or not.

**Comment by Zero3K** [comment]
I guess its not fixable then?

**Comment by rom1v** [comment]
Yes, without more specific information, this is not really a bug.

**Comment by Zero3K** [comment]
How do I give you more specific information?

**Comment by Zero3K** [comment]
I am attaching a log that has its level set to debug.

[gnirehtet log.zip](https://github.com/Genymobile/gnirehtet/files/923706/gnirehtet.log.zip)

**Comment by Zero3K** [comment]
I take it that its not of any help.
