### ISSUE TITLE
Windows 7 Incompatibility 

### ISSUE THREAD

**Issue by Rem1208** [Genymobile/gnirehtet#196]
I've have seen some clues regarding issue no. 66 it is that gnirehtet only works for the windows 10 version and not windows 7.It would be very lovely if you guys provide a file that can work on windows 7

**Comment by mksmbrtsh** [comment]
This application fine work on windows 7,8,10, astralinux, dude.

**Comment by rom1v** [comment]
@Rem1208 you need to find why `adb` does not detect your device on your Windows 7. Probably a driver issue. It's not directly related to _scrcpy_ or _gnirehtet_.
