### ISSUE TITLE
Cannot make it work with adb 1.0.41

### ISSUE THREAD

**Issue by khera7982** [Genymobile/gnirehtet#197]
Adb copied in directory,Adb is detecting device. apk installed directly from copying it to memory card. after running it gives error as below:

Cannot start client: Command adb ["shell", "dumpsys", "package", "com.genymobile.gnirehtet"] returned with value -1073740940

COnfig: windows 1064 bit
mobil: Note 8 samsung

**Comment by rom1v** [comment]
> Cannot start client: Command adb ["shell", "dumpsys", "package", "com.genymobile.gnirehtet"] returned with value -1073740940

Wow, `-1073740940` is very weird.

What if you execute manually:

    adb shell dumpsys package com.genymobile.gnirehtet

?

> windows 1064 bit

1064 bits? That explains things :trollface:

**Comment by khera7982** [comment]
Well it will be long before Win1064 is out....My Bad, typo on that part.
After manually executing the command i get the following output:

Receiver Resolver Table:
  Non-Data Actions:
      com.genymobile.gnirehtet.STOP:
        178e194 com.genymobile.gnirehtet/.GnirehtetControlReceiver filter 79c7e96
          Action: "com.genymobile.gnirehtet.START"
          Action: "com.genymobile.gnirehtet.STOP"
      com.genymobile.gnirehtet.START:
        178e194 com.genymobile.gnirehtet/.GnirehtetControlReceiver filter 79c7e96
          Action: "com.genymobile.gnirehtet.START"
          Action: "com.genymobile.gnirehtet.STOP"

Service Resolver Table:
  Non-Data Actions:
      android.net.VpnService:
        1ab543d com.genymobile.gnirehtet/.GnirehtetService filter 3cf49b1 permission android.permission.BIND_VPN_SERVICE          Action: "android.net.VpnService"

Key Set Manager:
  [com.genymobile.gnirehtet]
      Signing KeySets: 170

Packages:
  Package [com.genymobile.gnirehtet] (d0fbcd):
    userId=10344
    pkg=Package{dcba432 com.genymobile.gnirehtet}
    codePath=/data/app/com.genymobile.gnirehtet-eXRMpOp2Z3lxMs_FH81Z_A==
    resourcePath=/data/app/com.genymobile.gnirehtet-eXRMpOp2Z3lxMs_FH81Z_A==
    legacyNativeLibraryDir=/data/app/com.genymobile.gnirehtet-eXRMpOp2Z3lxMs_FH81Z_A==/lib
    primaryCpuAbi=null
    secondaryCpuAbi=null
    versionCode=6 minSdk=21 targetSdk=27
    versionName=2.3
    splits=[base]
    apkSigningVersion=2
    applicationInfo=ApplicationInfo{c685583 com.genymobile.gnirehtet}
    flags=[ HAS_CODE ALLOW_CLEAR_USER_DATA ]
    privateFlags=[ PRIVATE_FLAG_ACTIVITIES_RESIZE_MODE_RESIZEABLE_VIA_SDK_VERSION ]
    dataDir=/data/user/0/com.genymobile.gnirehtet
    supportsScreens=[small, medium, large, xlarge, resizeable, anyDensity]
    usesLibraries:
      org.apache.http.legacy
    usesLibraryFiles:
      /system/framework/org.apache.http.legacy.boot.jar
    timeStamp=2019-06-06 13:19:01
    firstInstallTime=2019-06-06 13:08:28
    lastUpdateTime=2019-06-06 13:19:05
    signatures=PackageSignatures{6c9bbd0 version:2, signatures:[34346c2c], past signatures:[]}
    installPermissionsFixed=true
    pkgFlags=[ HAS_CODE ALLOW_CLEAR_USER_DATA ]
    requested permissions:
      android.permission.INTERNET
      android.permission.ACCESS_NETWORK_STATE
    install permissions:
      android.permission.INTERNET: granted=true
      android.permission.ACCESS_NETWORK_STATE: granted=true
    User 0: ceDataInode=134110 installed=true hidden=false suspended=false stopped=false notLaunched=false enabled=0 instant=false virtual=false
      lastDisabledCaller: com.google.android.packageinstaller
      gids=[3003]
      runtime permissions:
    User 150: ceDataInode=0 installed=false hidden=false suspended=false stopped=true notLaunched=true enabled=0 instant=false virtual=false
      gids=[3003]
      runtime permissions:
mSkippingApks:
  package : (eBay)_idapk-1.0.0.26-2-DE-CS.apk
  package : 100Game_MOVISTAR_4x3_KU84_2009_2.0.9.apk
  package : 100Game_PERSONAL_4x4_PF36_2009_2.0.2.apk
  package : 4.4.4.Agosto(175).apk
  package : Adalyst_ZTA.apk
  package : AmazonMDIP-Android-1.0.51.0-release-signed-Sh-DE.apk
  package : CLAROAPPS_STUB_1_0_0.apk
  package : CLiP.apk
  package : ClaroContenedor_Stub.apk
  package : ClaroJuegos_Stub.apk
  package : EweMBMSServer_TEL.apk
  package : Fast.apk
  package : HPSClient.apk
  package : Ignite-globeIgniteAgent_5.4.037-4583_release.apk
  package : Ignite-singtelIgniteAgent_5.3.006-4495_release.apk
  package : KT114Provider2.apk
  package : KTCustomerService.apk
  package : KTHiddenMenu.apk
  package : KTOneStore.apk
  package : KTPushNotiService.apk
  package : KTServiceAgent.apk
  package : KTServiceMenu.apk
  package : LGUGPSnWPS.apk
  package : LGUHiddenMenu.apk
  package : LGUMiniCustomerCenter.apk
  package : LGUOZStore.apk
  package : LGUPlusBox.apk
  package : LGUSetting.apk
  package : LGUplusHDTV.apk
  package : LGUplusTsmProxy.apk
  package : MShopAndroidPhoneApp-16.5.0.100-build16.0.201246.0-patron-release-releasesigned.apk
  package : MaftPreloadManagerAndroidApp-MovistarMX.apk
  package : MaftPreloadManagerAndroidApp-TEF_LATAM.apk
  package : MaftPreloadManagerAndroidApp-release-signed-tagged.apk
  package : MeinVF-signed-7.7.5.apk
  package : MeuTIM.apk
  package : MiClaro_CDR_v5.1.apk
  package : MiClaro_CENAM_v2.0.1.apk
  package : MiClaro_CTI_v1.2.0-111.apk
  package : MiClaro_ECO_v3.6.1.apk
  package : MiClaro_PCT_v1.5.3_build67.apk
  package : MinhaClaro_v5.0.3-28.apk
  package : MinhaOi.apk
  package : MovitarPlayTGU_b_stub_v1.1_20180517.apk
  package : MyVodafone-production-R7.3_28_08_2018.apk
  package : MyVodafone_10.3.0_prodStore_store.apk
  package : MyVodafone_VFHU_v37.apk
  package : My_Singtel_4.4_com.singtel.mysingtel.apk
  package : My_Vodacom_V9.5.0.apk
  package : My_Vodafone_4.2.0.apk
  package : NaverV_N.apk
  package : ONEstoreSetupwizard.apk
  package : OiApps.apk
  package : OiAppsClube.apk
  package : OiRecarga.apk
  package : OiWiFi.apk
  package : Omc.apk
  package : OnStartNotification_v20.apk
  package : Portal_Stub.apk
  package : ProductSearch.apk
  package : SKTHiddenMenu.apk
  package : SKTMemberShip.apk
  package : SKTOneStore.apk
  package : SKTService.apk
  package : SafetyCleaner.apk
  package : SamsungClub_CTP_py_v3.3.4.apk
  package : SktUsimService.apk
  package : SmartPush.apk
  package : TPhoneOnePackage.apk
  package : TPhoneSetup.apk
  package : TStoreAgent.apk
  package : TStoreUtility.apk
  package : TelcelContenedorStub.apk
  package : TonosDeEspera_v1.6_20170123_omc_tgu_only.apk
  package : Upday.apk
  package : UserManual.apk
  package : VivoAppsClube.apk
  package : VivoMaisApps_Great.apk
  package : YelpPanel.apk
  package : app-release-Rel_4.25.apk
  package : appcloud_oobe_hutchison-release_V3.10.0.0.apk
  package : apps_brasil_signed_aligned.apk
  package : apt_Vodafone_StartOne_Katniss_v12.2.6_PROD_Samsung_signed.apk
  package : idapk-1.0.0.2-1.apk
  package : instagram-stub.apk
  package : instagram_stub.apk
  package : messenger-stub.apk
  package : miClaroPeru_Stub.apk
  package : miClaro_COM_Stub.apk
  package : miTelcel_Stub.apk
  package : mobileTworld.apk
  package : newMcare_AUTH_PROD_v3.3.7_CNX.apk
  package : newsstubv2.apk
  package : nfcagent-prodRelease-1.2.7.apk
  package : samsung_club_bo_4.3.4.apk
  package : samsung_club_uy_access_release_v1_3.apk
  package : samsung_concierge_argentina_stub.apk
  package : samsungclub_py_v3.3.4.apk
  package : signatureClub.apk
  package : trendystub_1.apk
  package : ubank_samsung.apk
  package : vfgr-myvf-4.6.3.1-3568AL-d180791-REL.apk
  package : wapp-1_0_6-22-without-ndk-signed.apk
  package : yandex.search.apk

Package Changes:
  Sequence number=649
  User 0:
    seq=1, package=com.android.stk
    seq=9, package=com.samsung.android.spayfw
    seq=10, package=com.google.android.partnersetup
    seq=48, package=com.gaana
    seq=89, package=com.facebook.appmanager
    seq=90, package=com.facebook.system
    seq=142, package=com.bigbasket.mobileapp
    seq=176, package=com.samsung.android.mobileservice
    seq=177, package=com.trivago
    seq=178, package=com.faultexception.reader
    seq=179, package=com.samsung.android.themestore
    seq=180, package=com.google.android.googlequicksearchbox
    seq=183, package=com.truecaller
    seq=184, package=com.languagedrops.drops.international
    seq=185, package=com.inn.nvengineer
    seq=186, package=com.google.android.apps.docs
    seq=187, package=net.one97.paytm
    seq=202, package=com.samsung.android.ipsgeofence
    seq=203, package=com.samsung.android.app.spage
    seq=283, package=com.amazon.mp3
    seq=284, package=xtracer.miband2funcbutton
    seq=419, package=com.facebook.services
    seq=452, package=com.google.android.keep
    seq=454, package=com.olacabs.customer
    seq=455, package=tw.mobileapp.qrcode.banner
    seq=458, package=com.lenovo.anyshare.gps
    seq=459, package=com.getmimo
    seq=460, package=com.stickotext.main
    seq=461, package=com.july.ndtv
    seq=462, package=com.ubercab.eats
    seq=463, package=com.sec.android.app.popupcalculator
    seq=464, package=com.netflix.mediaclient
    seq=488, package=mobi.charmer.fotocollage
    seq=508, package=com.google.android.gms
    seq=524, package=com.android.vending
    seq=525, package=com.astarsoftware.hearts
    seq=554, package=com.facebook.orca
    seq=577, package=com.androidapptest2113.atulkhera.takemed
    seq=581, package=com.samsung.android.messaging
    seq=620, package=com.floriandraschbacher.reversetethering.free
    seq=622, package=com.microsoft.skydrive
    seq=630, package=com.genymobile.gnirehtet
    seq=634, package=in.swiggy.android.daily
    seq=636, package=in.swiggy.android
    seq=648, package=com.sec.unifiedwfc
  User 150:
    seq=176, package=com.samsung.android.mobileservice
    seq=179, package=com.samsung.android.themestore
    seq=180, package=com.google.android.googlequicksearchbox
    seq=367, package=com.snapchat.android
    seq=418, package=com.cloudmosa.puffinFree
    seq=453, package=com.enflick.android.TextNow
    seq=510, package=com.google.android.gms
    seq=519, package=com.android.vending


Dexopt state:
  [com.genymobile.gnirehtet]
    path: /data/app/com.genymobile.gnirehtet-eXRMpOp2Z3lxMs_FH81Z_A==/base.apk
      arm64: [status=speed-profile] [reason=install]


Compiler stats:
  [com.genymobile.gnirehtet]
     base.apk - 532

Historical install Logging info(9/10):
  [com.floriandraschbacher.reversetethering.free]
    1559804286445: "Ver":"18", "Session":"0", "Write":"10564", "Commit":"674", "Stage":"23", "Init":"915", "Verified(Unk    nown)":"57", "Verified(Unknown)":"228", "Copy":"23", "Sign":"23", "DexOpt":"4",
  [com.android.vending]
    1559781455787: "Ver":"81512300", "Session":"0", "Write":"22", "Commit":"1285", "Stage":"115", "Init":"593", "Verifie    d(Unknown)":"73", "Verified(Unknown)":"218", "Copy":"45", "Sign":"103", "DexOpt":"20",
  [mobi.charmer.fotocollage]
    1559756111067: "Ver":"146", "Session":"0", "Write":"13843", "Write":"36777", "Write":"1659", "Commit":"7985", "Stage    ":"23", "Init":"1066", "Verified(Unknown)":"100", "Verified(Unknown)":"36", "Copy":"91", "Sign":"78", "DexOpt":"3",

  [com.androidapptest2113.atulkhera.takemed]
    1559802472025: "Ver":"1", "Session":"0", "Write":"107", "Write":"700", "Write":"535", "Write":"493", "Write":"660",
    "Write":"540", "Write":"520", "Write":"669", "Write":"548", "Write":"543", "Write":"560", "Write":"1075", "Write":"6    19", "Commit":"1678", "Stage":"16", "Init":"1067", "Verified(Unknown)":"13492", "Verified(Unknown)":"38", "Copy":"94    ", "Sign":"16", "DexOpt":"4",
  [com.genymobile.gnirehtet]
    1559807341001: "Ver":"6", "Session":"0", "Write":"11", "Commit":"355", "Stage":"4", "Init":"844", "Verified(Unknown)    ":"2683", "Verified(Unknown)":"161", "Copy":"36", "Sign":"1", "DexOpt":"5",
  [com.netflix.mediaclient]
    1559755960907: "Ver":"34268", "Session":"0", "Write":"15288", "Write":"14153", "Write":"3296", "Write":"1951", "Writ    e":"1898", "Commit":"818", "Stage":"651", "Init":"892", "Verified(Unknown)":"142", "Verified(Unknown)":"15", "Copy":    "49", "Sign":"59", "DexOpt":"44",
  [com.facebook.orca]
    1559756013764: "Ver":"157510619", "Session":"0", "Write":"25851", "Write":"6059", "Write":"1653", "Commit":"29084",
    "Stage":"114", "Init":"4981", "Verified(Unknown)":"87", "Verified(Unknown)":"14", "Copy":"174", "Sign":"144", "DexOp    t":"58",
  [com.sec.android.app.popupcalculator]
    1559755939674: "Ver":"1000111000", "Session":"0", "Write":"6907", "Write":"2443", "Commit":"446", "Stage":"6", "Init    ":"840", "Verified(Unknown)":"63", "Verified(Unknown)":"19", "Copy":"66", "Sign":"459", "DexOpt":"1",

**Comment by rom1v** [comment]
Is it with the rust or java version of gnirehtet?

**Comment by khera7982** [comment]
rust

**Comment by khera7982** [comment]
Any Ideas or shd i just try the Java one

**Comment by rom1v** [comment]
Oh, actually -1073740940 is a "valid" exit code on Windows: https://social.microsoft.com/Forums/en-US/6237ab2f-a4c3-47ea-9e90-652dc63081fd/exit-code-1073740940

It happens when there is a heap corruption. Which version of `adb` do you use?

**Comment by NracoW** [comment]
How do you check what version, I just downloaded it from the source files yesterday

**Comment by rom1v** [comment]
```
adb --version
```

**Comment by NracoW** [comment]
`Android Debug Bridge version 1.0.41
Version 29.0.0-5611747`

Is what I got back

**Comment by rom1v** [comment]
Just to be sure, could you test with another version, please? For example, the `adb.exe` from https://dl.google.com/android/repository/platform-tools_r28.0.1-windows.zip.

**Comment by NracoW** [comment]
Okay, yes! This was the issue, and now it is working just fine, thank you so much! 
Hopefully this is also the issue for who started the thread, haha

**Comment by andrei-lazarov** [comment]
I have the same issue. Guess it doesn't work with the latest adb?

**Comment by RoachWZ** [comment]
2019-08-19 14:21:40.646 INFO Main: Starting relay server...
2019-08-19 14:21:40.646 INFO Main: Checking gnirehtet client...
2019-08-19 14:21:40.646 INFO Relay: Relay server started
2019-08-19 14:21:44.802 INFO Main: Installing gnirehtet client...
gnirehtet.apk: 1 file pushed. 0.7 MB/s (21564 bytes in 0.032s)
        pkg: /data/local/tmp/gnirehtet.apk
Success
2019-08-19 14:21:46.740 INFO Main: Starting client...
Broadcasting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver }
Broadcast completed: result=0

**Comment by rom1v** [comment]
@RoachWZ Should be fixed by f8681809a28a0073f791f0d9eae65da02ae73c3d.

**Comment by rom1v** [comment]
Bug have been fixed since June in `adb`: https://developer.android.com/studio/releases/platform-tools

> - Hotfix for Windows crashes (https://issuetracker.google.com/134613180)
> - Fixes a Windows heap integrity crash.

Should work fine, now.
