### ISSUE TITLE
Cannot start client/ returned value -1073740940

### ISSUE THREAD

**Issue by NracoW** [Genymobile/gnirehtet#198]
Hello, after a few hours of troubleshooting I just cannot seem to get this to work, it always returns the error:
`2019-06-07 09:33:01.410 ERROR Main: Cannot start client: Command adb ["shell", "dumpsys", "package", "com.genymobile.gnirehtet"] returned with value -1073740940`
I have managed to set it up so that both java and adb are pathed propperly
It shows the device when I search for it

But still I can't seem to get this to work, I'm not usually someone who plays around with command prompt so is there something that I am missing?

My device is an android 7

**Comment by rom1v** [comment]
Which OS?

You get the same error as #197 posted yesterday.

**Comment by rom1v** [comment]
> I have managed to set it up so that both java

You use the Java version of gnirehtet?

**Comment by NracoW** [comment]
Oh yea I just noticed that and was actually about to comment there, whoops
I'm running windows 10
version is Java,

**Comment by rom1v** [comment]
https://github.com/Genymobile/gnirehtet/issues/197#issuecomment-499908755

**Comment by MarcR9** [comment]
ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

can anyone help me with this one :(

**Comment by rom1v** [comment]
Do you use 2.4 with the apk from 2.4?

Execute `./gnirehtet uninstall` and retry.

**Comment by MarcR9** [comment]
> Do you use 2.4 with the apk from 2.4?
what 2.4? I followed the steps from this guy https://www.youtube.com/watch?v=EHooYfSWvkI
> Execute `./gnirehtet uninstall` and retry.
I tried this just now but still same error :(

**Comment by KareemRabie** [comment]
Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

2020-01-20 17:06:23.683 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255


could you please help me?

**Comment by AhmedSufyan** [comment]
ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255
Kindly help

**Comment by rom1v** [comment]
You need adb: https://github.com/Genymobile/gnirehtet#adb

**Comment by AhmedSufyan** [comment]
ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255



> You need adb: https://github.com/Genymobile/gnirehtet#adb

ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

same error

**Comment by rom1v** [comment]
What is the result of `adb devices`?

**Comment by gmellocmr** [comment]
I'm getting the same error (returned value 255). Already tried reinstalling gnirehtet
And I have a device attached:
```
>adb devices
List of devices attached
11d95d25        device
```

**Comment by rom1v** [comment]
How do you start gnirehtet? From which directory? Which version?

**Comment by gmellocmr** [comment]
I've got this one:
https://github.com/Genymobile/gnirehtet/releases/download/v2.4/gnirehtet-rust-win64-v2.4.zip

But now it worked. There was another layer o UBS debugging (security configuration) I had to activate on my device (MIUI Global 11.0.6):
