### ISSUE TITLE
Tried it with two versions of ADB .39 and .40

### ISSUE THREAD

**Issue by MessedupBirdie** [Genymobile/gnirehtet#199]
Recently changed my phone, it's a new phone and this one isn't connecting. Gives following error.

2019-06-08 13:42:35.681 I Gnirehtet: Checking gnirehtet client...
2019-06-08 13:42:35.681 I Gnirehtet: Starting relay server...
2019-06-08 13:42:35.800 I Relay: Relay server started
2019-06-08 13:42:40.565 I Gnirehtet: Starting client...
Broadcasting: Intent { act=com.genymobile.gnirehtet.START flg=0x400000 cmp=com.g
enymobile.gnirehtet/.GnirehtetControlReceiver }
Broadcast completed: result=0

**Comment by rom1v** [comment]
Unfortunately, this is a recurrent problem. Some devices require to "authorize" the app manually, but each in different ways. See for example: https://github.com/Genymobile/gnirehtet/issues/161#issuecomment-455324982 and https://github.com/Genymobile/gnirehtet/issues/150#issuecomment-440989256.

I need to do something to avoid this problem…

**Comment by rom1v** [comment]
Should be fixed by f8681809a28a0073f791f0d9eae65da02ae73c3d.
