### ISSUE TITLE
Issues with nPerf

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#20]
When I run the full speed test, I am noticing the following issues:

1. The Upload Speed starts out high then gets really low at the end.
2. It cannot determine the Latency.
3. Some sites it uses for the Site Load Speed test are timing out.

**Comment by rom1v** [comment]
> 2. It cannot determine the Latency.
> 3. Some sites it uses for the Site Load Speed test are timing out.

Only TCP and UDP are forwarded. The other tests probably uses other protocols (typically ICMP for ping).

**Comment by Zero3K** [comment]
Regarding number 3, Its not occurring for all of them though. Its like one of the pages doesn't finish loading for some reason.

**Comment by rom1v** [comment]
> Its like one of the pages doesn't finish loading for some reason.

Does it still happen on latest release?

**Comment by Zero3K** [comment]
Yes, it is still happening.

**Comment by rom1v** [comment]
Without more information, I'm closing. Feel free to reopen if necessary.
