### ISSUE TITLE
SHARE GNIREHTET INTERNET USING HOTSPOT?

### ISSUE THREAD

**Issue by niche710** [Genymobile/gnirehtet#204]
Is there possible way to share the internet connection using my hotspot? thanks

**Comment by rom1v** [comment]
No, see #200.

**Comment by zyx486013** [comment]
you can try this:https://github.com/xinruoyusixian/android-reverse-tethering-master
I modify a Xray version of this :https://github.com/zyx486013/android-reverse-tethering-v2-win7x86
Based on my testing, the Xray version supports VPN Hotspot or the built-in SOCKS proxy.
