### ISSUE TITLE
Can You Chain Connections?

### ISSUE THREAD

**Issue by BoxWizard000000** [Genymobile/gnirehtet#205]
I'm using this on a raspberry pi that is connected to a computer via ethernet. The computer is sharing its internet with the pi. 

When I try to connect my Samsung Galaxy Tab A to the Raspberry Pi, the connection is not seen.

**Comment by rom1v** [comment]
> When I try to connect my Samsung Galaxy Tab A to the Raspberry Pi, the connection is not seen.

Concretely, what do you do?

What do you mean by "the connection is not seen"?

**Comment by BoxWizard000000** [comment]
I have an apache web server displaying a custom web page that acts like a form a user can fill out information in. I can connect just fine from my pi by typing in the IP of the server. Next, I use Gnirehtet on the raspberry pi and connect my Samsung Galaxy Tab A to it. The VPN is established and I try to connect to the LAN network from my Galaxy Tab A and it doesn't seem to work.

I had thought that this works by establishing a VPN to whatever network the host is connected to. In this case, the host is a raspberry pi connected to a LAN network, but I'm not seeing the server and I cannot connect to the webpage.

**Comment by rom1v** [comment]
If it works when you connect to `http://xx.xx.xx.xx/page.html` from your pi, then it should work to connect to `http://xx.xx.xx.xx/page.html` from your device.

_(If `xx.xx.xx.xx == 127.0.0.1`, you must replace it by `10.0.2.2`.)_

Could you paste gnirehtet logs?

**Comment by rom1v** [comment]
If it works when you connect to `http://xx.xx.xx.xx/page.html` from your pi, then it should work to connect to `http://xx.xx.xx.xx/page.html` from your device.

_(If `xx.xx.xx.xx == 127.0.0.1`, you must replace it by `10.0.2.2`.)_

Could you paste gnirehtet logs?

**Comment by BoxWizard000000** [comment]
Ok nevermind. I figured out that I was calling autostart vs. autorun. I have another issue starting directly from Ubuntu I'll post the logs for in another report. Sorry for the trouble.
