### ISSUE TITLE
Fixing the issues mentioned by Android Studio

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#21]
Maybe you could fix the ones that are mentioned by it when analyzing the source code.

**Comment by rom1v** [comment]
Which are?

**Comment by Zero3K** [comment]
The ones in the html file included in the attached ZIP file.

[Inspection Report.zip](https://github.com/Genymobile/gnirehtet/files/917669/Inspection.Report.zip)

**Comment by ewoks** [comment]
This is getting ridiculous @Zero3K .. Man, this is not facebook, no?

You are free to fork, make corrections, create pull request and any suggestion will be discussed and might be accepted or rejected if not relevant. Opening issues for such a things that you are doing is annoying, distracting and contra productive. 

If you found some **real** bug make new issue. But please stop with writing every single thought or idea that you have. Let's not make it noisy and allow developer to focus on issues.

**Comment by rom1v** [comment]
@Zero3K `gradle build` already executes _lint_ and _checkstyle_.

The rules of _Android Studio_ inspection generate many false positives. That's good to check them once from time to time, just in case, but most of the reports are irrelevant.

I just removed some unnecessary `return` and added some `final`, but that's all.

---

That's great to report issues, but to go in the same direction as @ewoks, you should improve the way to report some of them.

No:

> some of my applications seems slow, here are all the logs, please check

but:

> I did this, I expected this, I get that. Here are the reasons why this problem does not come from x, y and z, this is why I think this is a bug in _gnirehtet_

Even reporting code style issues is great, but rather:

> I used this tool to analyze the code, those particular points seem relevant, because…

than:

> fix all what X tools reports

That way, we could be more efficient ;-)

As far as I remember, this article was great: [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
