### ISSUE TITLE
Background activity start from gnirehtet blocked (android q beta 5)

### ISSUE THREAD

**Issue by bughit** [Genymobile/gnirehtet#212]
2.3 `gnirehtet.exe run` fails to start the vpn 

https://developer.android.com/preview/privacy/background-activity-starts

You can work around it in dev opts, but it seems that apps started in a privileged way through adb should be exempt from this and shouldn't need a global loosening pref, so perhaps it's worth reporting this.

Also with q beta 5, I don't think android itself and some apps are aware that the network is up when gnirehtet is active, there's less activity in gnirehtet.exe output, and some apps refuse to connect (e.g, podcast addict), compared to android 8.1

**Comment by cloudbank** [comment]
please fix this! allowing background activity starts in developer options occludes bugs that need to be found / fixed in apps being tested under Q beta

**Comment by rom1v** [comment]
Could you test with current `master`, please?

f8681809a28a0073f791f0d9eae65da02ae73c3d may have fixed the bug (since we start the activity only from command line with shell rights).

**Comment by bughit** [comment]
I am no longer experiencing this is the final release of android 10. They changed something, I don't thing the dev opt originally mentioned in the link even exists
