### ISSUE TITLE
[Feature request] simulate wifi

### ISSUE THREAD

**Issue by thegamerx1** [Genymobile/gnirehtet#216]
Do some type of simulation that it has wifi connection because some apps check if wifi is on to tell if there is internet or not

**Comment by alw1746** [comment]
Yes I support this great idea.  With gnirehtet  I still cannot download magazines from rbdigital.com as the android app insists on wifi being connected.

**Comment by rom1v** [comment]
I don't know any technical solution for this.

**Comment by CodeJoule** [comment]
I suppose you could connect to any nearby open network (even if login page appears, just ignore it) and just enable gnirehtet with whatever setup you already have. The app could then proceed, thinking the internet connection is coming from the WiFi router as opposed to gnirehtet. That's all if there is an open network nearby.
