### ISSUE TITLE
Configure Homebrew Formulae

### ISSUE THREAD

**Issue by SalvatoreT** [Genymobile/gnirehtet#238]
I think it would be pretty sweet if you could easily `brew install gnirehtet` in the same way you `brew instal scrcpy`.

**Comment by SalvatoreT** [comment]
You can now run

```
brew install gnirehtet
```

or if you want the latest and greatest

```
brew install gnirehtet --HEAD
```

**Comment by rom1v** [comment]
Wow, thank you :+1: :tada:

(A little request: could you please update it to v2.4, which fixes problems on Android >= 8?)

**Comment by SalvatoreT** [comment]
@rom1v, you're welcome!

I opened #249 to track the Homebrew update to v2.4.

There's currently a [hack in the Homebrew formulae](https://github.com/Homebrew/homebrew-core/blob/4e3b3a4fd48d1840bafaf62d892fbbcf3c1fc6fd/Formula/gnirehtet.rb#L22-L31) that overwrites the `install` command. The `install` command currently assumes the Android APK is in the current directory. If there was a way to set the APK directory at compile time for Rust, I could take out this hack. Here's some other folks discussing the issue: #90.
