### ISSUE TITLE
Issue with Kingdom Hearts Union x

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#24]
It times out when downloading the full game by tapping the Download button when its shown after completing the tutorial stages of it.

**Comment by Zero3K** [comment]
Why the thumbs down? Is it because I'm not detailing it enough?

**Comment by oldmud0** [comment]
That's correct. What are you seeing on the relay server log when you tap the Download button? Does it work when gnirehtet is not being used?

**Comment by Zero3K** [comment]
1. It mentioned dropping invalid packets, etc.
2. Yes, it works when not using gnirehtet.

**Comment by rom1v** [comment]
The symptoms look similar to https://github.com/Genymobile/gnirehtet/issues/48. Do you see any particular IP that timeouts in the logs?

**Comment by rom1v** [comment]
Without more information, I'm closing. Feel free to reopen if necessary.
