### ISSUE TITLE
OnePlus 7 Pro cannot connect \ Android Q 

### ISSUE THREAD

**Issue by sonderlau** [Genymobile/gnirehtet#246]
Based on Hydrogen OS Android Q 
cannot connect to any network.
My phone info:
Hydrogen OS 10.0.1.GM21
12GB+256GB
Kernel Veison : 4.14.117-perf+
Baseband version : MPSS.HE 1.0.C11.1-00007_SM8150_GEN-PACK-2.225821.1.22.7239.1

Windows 10

**Comment by rom1v** [comment]
Could you paste the output of gnirehtet when you run it?

**Comment by sonderlau** [comment]
![图片](https://user-images.githubusercontent.com/12829325/69908863-9dfde480-142c-11ea-9805-6823533d7aea.png)
![图片](https://user-images.githubusercontent.com/12829325/69908866-a524f280-142c-11ea-9177-5a10cc3fc846.png)
![图片](https://user-images.githubusercontent.com/12829325/69908874-c1c12a80-142c-11ea-93c3-604b11c19a65.png)
![图片](https://user-images.githubusercontent.com/12829325/69908875-c4238480-142c-11ea-9a6a-05aed31cd3a1.png)

**Comment by sonderlau** [comment]
that's not only happened on the browser, the same as the AppStores , apps , games etc. Just no internet

**Comment by rom1v** [comment]
Can you access google DNS (8.8.8.8) from your computer?

If not, pass your dns:

    gnirehtet run -d ip.ip.ip.ip

**Comment by sonderlau** [comment]
> 
> 
> Can you access google DNS (8.8.8.8) from your computer?
> 
> If not, pass your dns:
> 
> ```
> gnirehtet run -d ip.ip.ip.ip
> ```

In China , Google is banned according to GreatFireWall . And when i change the dns server, it's finally worked. I hope you can add these tips in reademe for the people who live in the country that cannot connect google smoothly ,
Thanks.
