### ISSUE TITLE
Issue with downloading files hosted via HFS

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#25]
When I download a large file that has been hosted via HFS (http://www.rejetto.com/hfs/) when connected via gnirehtet, the speed of the download fluctuates and I notice lots of "ignoring packet" and "unexpected first packet" errors in the log.

**Comment by rom1v** [comment]
> I notice lots of "ignoring packet" and "unexpected first packet" errors in the log

The important thing to look at is whether a packet is sent and resent forever by the device but never considered by the relay server.

This is suggested by an "infinity" of "ignoring packet" for the same sequence number (for the same connection) while the acknowledgment number does not increase (more details given when loglevel is set to `LogLevel.DEBUG`).

If there are only few of identical "ignoring packets", then the connection has recovered and everything is ok.

> the speed of the download fluctuates

Does it fluctuates when not using _gnirehtet_?

**Comment by Zero3K** [comment]
1. Ok. I am attaching a log that's set to DEBUG level to see if it helps any.
2. I am using it to transfer files via USB since it takes way too long to transfer them via copying using Windows Explorer. So, I don't know how I can do the same thing without it.

[gnirehtet log.zip](https://github.com/Genymobile/gnirehtet/files/923689/gnirehtet.log.zip)

**Comment by rom1v** [comment]
> I am using it to transfer files via USB

Why don't you simply use `adb push`?

> I am attaching a log that's set to DEBUG level to see if it helps any.

The log file is more than 500Mb, with almost 5 millions lines. No, it does not help any :)

In these logs too the connections to `10.0.1.85:443` fail.

**Comment by Zero3K** [comment]
The way I'm doing it is working well for me. Just could be better, is all.
