### ISSUE TITLE
Rust_v2.4 is not working with VPN tethering

### ISSUE THREAD

**Issue by fuminchao** [Genymobile/gnirehtet#253]
The network connected to wifi tether on the device tunneling by gnirethet, is not working

Error message on the stdout with env ```RUST_BACKTRACE=1```
```WARN Router: Dropping invalid packet```

**Comment by rom1v** [comment]
Please post more logs. `Dropping invalid packet` is expected when the protocol is not TCP or UDP.

**Comment by fuminchao** [comment]
There is no other log line for this error, even with ```RUST_BACKTRACE=1```

**Comment by fuminchao** [comment]
Let me put more details
a. I setup gnirehtet on android, and it works fine.
b. then, I enable wifi tethering on the device, with proper iptables settings
c. connect my iphone to the tethering hotspot, and try to open google.com, but connection errors
d. There is only one line of log printed on stdout ```Router: Dropping invalid packet```

**Comment by rom1v** [comment]
> b. then, I enable wifi tethering on the device, with proper iptables settings

You can't use gnirehtet with wifi tethering. See #126.
