### ISSUE TITLE
No response in Android 10

### ISSUE THREAD

**Issue by rajkumaar23** [Genymobile/gnirehtet#279]
```
2020-03-10 21:41:37.740 INFO Main: Starting relay server...
2020-03-10 21:41:37.740 INFO Main: Checking gnirehtet client...
2020-03-10 21:41:37.740 INFO Relay: Relay server started
2020-03-10 21:41:37.827 INFO Main: Starting client...
Broadcasting: Intent { act=com.genymobile.gnirehtet.START flg=0x400000 cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver }
Broadcast completed: result=0
```
Above is what is displayed in the terminal and no response is shown in the mobile.

Device : Redmi Note 4 running Evolution X (Android 10)
PC : Linux Mint 19.3 Tricia

**Comment by Biswa96** [comment]
If that is running MIUI then try to install the APK file from here https://github.com/Biswa96/gnirehtet-miui/releases. Then run `gnirehtet start; gnirehtet relay` in terminal in PC.

**Comment by rajkumaar23** [comment]
I've mentioned it's running [Evolution X](https://evolution-x.org/)

**Comment by rajkumaar23** [comment]
@Biswa96 No, it doesn't help.

**Comment by rom1v** [comment]
> Broadcast completed: result=0

You don't use the last version.

**Comment by rajkumaar23** [comment]
> > Broadcast completed: result=0
> 
> You don't use the latest version.

The apk or Linux binary?

**Comment by rajkumaar23** [comment]
> > Broadcast completed: result=0
> 
> You don't use the latest version.

Actually yes! Thanks a lot :+1:
