### ISSUE TITLE
Chromecast not detected on LAN

### ISSUE THREAD

**Issue by tmiland** [Genymobile/gnirehtet#288]
Hi,

trying to get this working using my cellphone as a remote for ChromeCast on LAN without using WiFi,
but for some reason it's not detecting it.

Any chance this can be fixed? As using ChromeCast on a laptop is quite limited...

**Comment by rom1v** [comment]
No, it won't work. _gnirehtet_ forwards TCP and UDP initiated from the device.

**Comment by tmiland** [comment]
> No, it won't work. _gnirehtet_ forwards TCP and UDP initiated from the device.

Okay, thanks.
