### ISSUE TITLE
gnirehtet question reverse tether

### ISSUE THREAD

**Issue by everiles** [Genymobile/gnirehtet#290]
Hi. gnirehtet helped me a lot, but I have some questions. Now I have new phone and I want to create a hotspot Wi-Fi (because i dont have router in my house) that will connect my second phone. 
Reverse tether works well but only in phone that is connected through USB. There is a internet connection, but when i create a hotsport WiFi the second phone don't have the internet. Could you help me? I'm amateur... propably that is very simple for you guys

**Comment by rom1v** [comment]
It does not work with hotspot wifi. #95
