### ISSUE TITLE
Viber

### ISSUE THREAD

**Issue by zalaross** [Genymobile/gnirehtet#30]
I made some tests and it seems that if viber is closed and I start gnirehtet then viber can't connect online. But if I have viber running and connected online via gprs and then start gnirehtet and shutdown gprs then viber stays connected and works ok.

**Comment by rom1v** [comment]
Thank you for reporting the issue.

Could you paste the logs generated by _gnirehtet_ when _Viber_ fails to connect, please?

**Comment by zalaross** [comment]
Now that I've tried to take the logs it works perfectly. Weird stuff. It's the first time that viber works with gnirehtet. It didn't fail to connect but it kept stuck in connecting. I'll close the issue as it seems that it's viber's issue and not gnihertet's. Thank you.

**Comment by rom1v** [comment]
OK, feel free to reopen if you reproduce with logs :)
