### ISSUE TITLE
Set worked but no internet on proxy ethernet connection

### ISSUE THREAD

**Issue by Coolboyrajat** [Genymobile/gnirehtet#315]
Setup completely worked but no internet connection established on proxy ethernet connection. Can anyone suggest me anything to change in settings

**Comment by rom1v** [comment]
https://github.com/Genymobile/gnirehtet/issues/27#issuecomment-296404498

**Comment by Coolboyrajat** [comment]
Anything will be great if it is in video format. I don't know much about commands just copy paste
