### ISSUE TITLE
Failure to connect to Android 7.1.2

### ISSUE THREAD

**Issue by nikolakoco89** [Genymobile/gnirehtet#32]
Hello, I’m trying to start gnirehtet, but unsuccessfully. I’m getting the notification on the android device (7.1.2), but I’m unable to click ok(it’s not possible), only cancel. The device is an Nexus 5x, build number N2G470
[log.txt](https://github.com/Genymobile/gnirehtet/files/1057775/log.txt)

**Comment by rom1v** [comment]
I had this problem once when I updated from Android 6 to Android 7 while _gnirehtet_ was installed.

The reason is the change of the uid associated to the app. In your logs:

    Bad call: specified package com.genymobile.gnirehtet under uid 10038 but it is really 10119

Reinstalling should solve the problem:

    ./gnirehtet reinstall

**Comment by nikolakoco89** [comment]
Thank you, it worked. Sorry for replying so late.
