### ISSUE TITLE
Does not work for Android 4.2.2

### ISSUE THREAD

**Issue by yacosta93** [Genymobile/gnirehtet#33]
Gnirehtet is made for android versions older than 4.2.2 because I have a mobile with that version and it does not work for me. My email is yunielacosta738@gmail.com

**Comment by rom1v** [comment]
In the [requirements](https://github.com/Genymobile/gnirehtet/blob/master/README.md#requirements):
> The Android application requires at least API 21 (Android 5.0).
More details [here](https://github.com/Genymobile/gnirehtet/issues/2).
