### ISSUE TITLE
How can I stop this?

### ISSUE THREAD

**Issue by nkgcp** [Genymobile/gnirehtet#332]
I'm using your program on Windows 10.
Once I execute `.\gnirehtet.exe run`, I can't enter anything.
Even if I open another window and enter `.\gnirehtet.exe stop` or stop from phone, the internet connection is closed, but you can still enter nothing.
Using 'ctrl+c' closes the internet connection with the message below.
```
2020-10-04 20:15:35.791 INFO Main: Interrupted
2020-10-04 20:15:35.791 INFO Main: Stopping client...
Starting: Intent { act=com.genymobile.gnirehtet.STOP cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
2020-10-04 20:15:35.931 ERROR UdpConnection: 10.0.0.2:65492 -> 8.8.8.8:53 Cannot read: [Other] Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
thread '
```
This happens in both cmd and powershell.
![image](https://user-images.githubusercontent.com/65478530/95014325-0b982400-0681-11eb-99b1-192695f0b19c.png)
![Screenshot (3)](https://user-images.githubusercontent.com/65478530/95014413-96791e80-0681-11eb-97ab-9c702559274d.png)

**Comment by rom1v** [comment]
> Once I execute `.\gnirehtet.exe run`, I can't enter anything.

That's expected. What do you want to enter?

**Comment by nkgcp** [comment]
> That's expected. What do you want to enter?
I wanna execute `.\gnirehtet.exe stop`
> Then does it correctly stop the application?
What does this mean? I am not good at English.
