### ISSUE TITLE
Not able to resolve domains from DNS server (firewall issue?)

### ISSUE THREAD

**Issue by Nexteme** [Genymobile/gnirehtet#337]
I am developing in an offline environment/WAN.  The tethering tool works great for IP addresses however when I try to use DNS names I don't get any DNS resolution.

I am running the relay server with the _-d_ option and specifying the IP address of my DNS server.  I am seeing that IP address instead of 8.8.8.8 in the log for the relay server now, so to me that means it should be working.  However, any request from my Android device app or browser doesn't seem to be able to resolve to an IP.

We have a lot of firewalls in our network.  I have ensured that ICMP has been opened.  Can you think of what else may be blocking?  The network team doesn't seem to see anything being blocked.

**Comment by rom1v** [comment]
> However, any request from my Android device app or browser doesn't seem to be able to resolve to an IP

Does your network require a HTTP proxy?

**Comment by Nexteme** [comment]
> > However, any request from my Android device app or browser doesn't seem to be able to resolve to an IP
> 
> Does your network require a HTTP proxy?

No

**Comment by Nexteme** [comment]
I'm wondering if the firewall or DNS server can detect the originating IP of the message.  Is there a different IP than my host being used to create these requests?

**Comment by rom1v** [comment]
The TCP/UDP connection is initiated by your host, so the IP is that of the host.

**Comment by Nexteme** [comment]
I see in the logs every once and a while,
........xxx.xxx.xxx.xxx:853 Cannot read: [ConnectionRefused] No connection cold be made because the target machine actively refused it. (os error 10061)

**Comment by rom1v** [comment]
So you can't connect to xxx.xxx.xxx.xxx:853 from your host.

**Comment by Nexteme** [comment]
Just ran in PowerShell **Test-NetConnection <host> -port 853** and it returns successful ping but failed the TCP connection

**Comment by Nexteme** [comment]
I assume that is the issue?  Is TCP required on that port to the DNS server?

**Comment by rom1v** [comment]
Is xxx.xxx.xxx.xxx the DNS server? Often, DNS requests are on UDP.

**Comment by Nexteme** [comment]
Yes it is.  I do see successful connections on port 53

**Comment by Nexteme** [comment]
So looking at the gnirehtet logs, the port 53 connections say "UdpConnection" and the port 853 ones are TcpConnection

**Comment by Nexteme** [comment]
Is the TcpConnection to 853 supposed to be a TLS connection?

**Comment by Nexteme** [comment]
Perhaps those errors have nothing to do with my issue.  Do you have any ideas where I should start looking to debug the issue?  I assume it isn't the projects code as it appears many others out there are using an alternate DNS server.  I am using Windows 10 as my host.
I did try to build the project however I am offline and keep getting errors trying to download a specific version of gradle, which I have downloaded manually and placed in the correct spot.  I develop my Android apps in Xamarin so not a ton of experience in Android Studio.

**Comment by rom1v** [comment]
Port 853 is used for DNS over TLS, so I think it's related to your problem.

Try to disable DNS over TLS in your browser to confirm.

**Comment by Nexteme** [comment]
Ok, on the phone I found the setting **Private DNS** on the device and set it to off.  Now all of a sudden no errors and everything is working!!!

Thanks for the assistance.
