### ISSUE TITLE
Raspbian Jessie 8 with Acer B3-A330

### ISSUE THREAD

**Issue by nikolakoco89** [Genymobile/gnirehtet#34]
Hello, 
Previously I had opened an issue about connecting Nexus 5X, which was resolved. Now I have another problem, but this time with an Acer tablet B3-A330 with Android 6.0. On Windows 7 it worked perfectly, but I'm trying to use it on Raspberry Pi with Raspbian Jessie 8, and I can't connect it. Attached you can find logcat output
[logcat.txt](https://github.com/Genymobile/gnirehtet/files/1084794/logcat.txt)

**Comment by nikolakoco89** [comment]
I have the same problem with the Nexus 5x, Android 7.1.2 and the Raspberry Pi with Raspbian Jessie 8

**Comment by rom1v** [comment]
In the logs, I see:

    GnirehtetControlService: Received request com.genymobile.gnirehtet.STOP

But never the `START`request.

Anyway, this is the relay server that runs on the Raspberry (logcat is what happen on the Android side). What do the server logs say?

**Comment by nikolakoco89** [comment]
I only get: "Main: Starting server...", but I guess that this is only logging level info.

**Comment by rom1v** [comment]
In another terminal, execute:

    adb reverse tcp:31416 tcp:31416
    adb shell am startservice -a com.genymobile.gnirehtet.START

What does it say?

Is the `START` visible in `adb logcat`?

What is the result of:

    adb version
    adb reverse --list

?

**Comment by nikolakoco89** [comment]
Attached you can find the outputs of the terminal and logcat
[logcat.txt](https://github.com/Genymobile/gnirehtet/files/1088146/logcat.txt)
[terminal_output.txt](https://github.com/Genymobile/gnirehtet/files/1088147/terminal_output.txt)

**Comment by rom1v** [comment]
OK, the cause is that your `adb` (1.0.31) does not support `adb reverse`. You need a more recent version of `adb`. I know that 1.0.36 supports it.

**Comment by nikolakoco89** [comment]
Ok, I will try to get it to the raspbian, I use android-tools-adb right now and the latest version is 1.0.31. Thanks a lot

**Comment by numanair** [comment]
@nikolakoco89 Were you able to get this working?

**Comment by rom1v** [comment]
Note that v1.1 should work even on older versions of `adb`, since it now fallbacks to `adb forward` when `adb reverse` does not work.

**Comment by numanair** [comment]
I've got it to a point where it says:
E Gnirehtet: Cannot start client
com.genymobile.gnirehtet.relay.CommandExecutionException: Command [adb, reverse, localabstract:gnirehtet, tcp:31416] returned with value 1

Is this where it should be falling back? I am also on adb 1.0.31

**Comment by numanair** [comment]
I just got it working using ADB 1.0.37 found here: https://github.com/bonnyfone/adb-arm/issues/5
I'm surprised to see speed tests report it's slower than my wifi, but I don't mind too much as I mainly wanted to reduce congestion.

**Comment by rom1v** [comment]
@numanair Do you use the _Rust_ or _Java_ version?

**Comment by numanair** [comment]
I'm using the Rust version.
