### ISSUE TITLE
gnirehtet automatically stops after running for average 6 mins in cmd 

### ISSUE THREAD

**Issue by hDmtP** [Genymobile/gnirehtet#341]
Although I keep opening the command prompt window in my PC, the running program shows the following error after a fixed period of time: 

"2020-11-17 01:07:35.749 INFO TunnelServer: Client #0 disconnected"

Now, this is not a big deal. You can simply re-run the command by just pressing the upper arrow key and enter. But when I play multiplayer online games(i.e. PUBG, Free Fire, Call of Duty, Among Us) it is certainly disheartening(I hope you can get me).

Is there any solution to this problem? 
Android Version 9.2

**Comment by rom1v** [comment]
I guess this is an adb disconnection. For example if you run `adb logcat` at the same time, it should also stop. Could you confirm?

**Comment by hDmtP** [comment]
Checking.....

**Comment by hDmtP** [comment]
Yeah, the command is doing its job.
But why it disconnects automatically even if don't run adb logcat manually?

**Comment by rom1v** [comment]
> Yeah, the command is doing its job.

Run `adb logcat` in a separate terminal: it should not terminate until you disconnect the device (it continues to print logs).
As soon as the connection is lost, it should terminate and give prompt back.

Does it terminate exactly at the same time as gnirehtet shows "connection stopped"? (Is it what you tested?)

---

If not, when gnirehtet stops, could you post the content of `adb logcat`?

```bash
adb logcat -c  # clear
./gnirehtet run
adb logcat -d > logcat.txt
```

**Comment by hDmtP** [comment]
Sure, give me some time

**Comment by hDmtP** [comment]
Yes, it works absolutely as you described in the first para.

![Screenshot (572)](https://user-images.githubusercontent.com/65482473/99365004-ba648c80-28dc-11eb-958b-efc4dd4c2f85.png)

**Comment by hDmtP** [comment]
What next??

**Comment by rom1v** [comment]
`adb logcat` continues to print logs even once gnirehtet is disconnected unexpectedly?

**Comment by hDmtP** [comment]
> `adb logcat` continues to print logs even once gnirehtet is disconnected unexpectedly?

YES

**Comment by rom1v** [comment]
Then please post your `logcat.txt` as explained in https://github.com/Genymobile/gnirehtet/issues/341#issuecomment-728736005.

**Comment by hDmtP** [comment]
[logcat.txt](https://github.com/Genymobile/gnirehtet/files/5565504/logcat.txt)

**Comment by hDmtP** [comment]
> [logcat.txt](https://github.com/Genymobile/gnirehtet/files/5565504/logcat.txt)
> is this what you wanted?

***IS THIS WHAT YOU WANTED***

**Comment by rom1v** [comment]
Yes. But I see nothing special.

Only this error, but since `CLOSE_VPN` is received, that's expected:
```
11-19 14:09:35.241  7325  7325 D GnirehtetService: Received request com.genymobile.gnirehtet.CLOSE_VPN
11-19 14:09:35.246  1162  1162 I VNOILNMS: ===VNOILNMS n=0 VideoStates=false NoticeStates=false flag_red=0 flag_green=0 mScreenOn=true mNotificationPulseEnabled=true
11-19 14:09:35.247  1162  1162 D NotificationService: 0|com.genymobile.gnirehtet|42|null|10144: updating permissions
11-19 14:09:35.247  1162  1162 D NotificationService: 0|com.genymobile.gnirehtet|42|null|10144: destroying owner
11-19 14:09:35.247  1162  1162 D NotificationService: handleSavePolicyFile
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: Cannot receive from tunnel
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: java.lang.InterruptedException
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at java.lang.Object.wait(Native Method)
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at java.lang.Object.wait(Object.java:422)
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.RelayTunnelProvider.waitUntilNextAttemptSlot(RelayTunnelProvider.java:120)
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.RelayTunnelProvider.getCurrentTunnel(RelayTunnelProvider.java:61)
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.PersistentRelayTunnel.receive(PersistentRelayTunnel.java:63)
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.Forwarder.forwardTunnelToDevice(Forwarder.java:126)
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.Forwarder.access$300(Forwarder.java:34)
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.Forwarder$2.run(Forwarder.java:73)
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-19 14:09:35.248  7325  7343 E PersistentRelayTunnel: 	at java.lang.Thread.run(Thread.java:764)
11-19 14:09:35.248  7325  7343 D Forwarder: Device to tunnel interrupted
```

Does the problem occur both with the Rust and the Java versions?

**Comment by hDmtP** [comment]
Well, I'm using the rust version as per your README.MD suggestion. Btw what is the exact time 'gnirehtet' is supposed to run without being interrupted?

**Comment by hDmtP** [comment]
> Well, I'm using the rust version as per your README.MD suggestion. Btw what is the exact time `gnirehtet.cmd` is supposed to run without being interrupted?

????!!

**Comment by rom1v** [comment]
> Well, I'm using the rust version as per your README.MD suggestion.

Yes, but knowing if it also happens in the Java version could help localize the problem.

> >  `adb logcat` continues to print logs even once gnirehtet is disconnected unexpectedly?
>
> YES

It's weird :/

Just to confirm, you start `adb logcat` (keep it open), then you start `gnirehtet run` in another terminal.
When you get `INFO TunnelServer: Client #0 disconnected` in `gnirehtet`, `adb logcat` is still running?

**Comment by hDmtP** [comment]
checking.....

**Comment by hDmtP** [comment]
NO no, not this time.

I checked it multiple times and `adb logcat` stops running while `gnirehtet` shut down unexpectedly .

**Comment by hDmtP** [comment]
GUT why does gnirehtet shuts down unexpectedly?? Can you please explain??!

**Comment by rom1v** [comment]
It's just due to an adb disconnection then. Either the adb server crashes on the device, or the USB cable or USB port has some problem.

**Comment by hDmtP** [comment]
> It's just due to an adb disconnection then. Either the adb server crashes on the device, or the USB cable or USB port has some problem.

I think the android debugging bridge crashes on my laptop as there is no problem with my USB port and cable.
