### ISSUE TITLE
Gnirehtet VPN treated as metered?

### ISSUE THREAD

**Issue by AliffanI** [Genymobile/gnirehtet#342]
Hi there,

Whenever I start gnirehtet, apps that are in the middle of a download throw messages like "Waiting for WiFi" or "Waiting for network." And while gnirehtet is running, apps like, say, the Play Store and Chrome pauses new downloads, saying that I need to connect to a WiFi network even though I'm already connected to one. I can force apps to go on with their downloads, but some just refuse to. Could this be because Android treats gnirehtet's VPN connection as metered?

I don't know anything about developing, but I found [this](https://developer.android.com/reference/android/net/VpnService.Builder#setMetered(boolean)) while searching for a way to make Android treat VPNs as unmetered. Does gnirehtet already mark itself as an unmetered VPN? (Or can setMetered be used at all, considering that it was added in a recent API level.) If it already does, what else could be making apps refrain from going through with their transfers?

Sincerest apologies if I got this wrong, or if this has been covered in a previous issue already.

**Comment by rom1v** [comment]
Ref: #37

> A VPN network is classified as metered when the user is sensitive to heavy data usage due to monetary costs and/or data limitations. In such cases, you should set this to true so that apps on the system can avoid doing large data transfers.

IMO this is unrelated.

**Comment by AliffanI** [comment]
Oh, I thought since the apps' download behavior on gnirehtet (or some other VPN services, while connected to WiFi manually set as unmetered) is similar to their behavior on a WiFi manually set as metered, Android's metered/unmetered network treatment might've been related to the problem in some way... I guess I don't fully understand how gnirehtet works (or even how Android VPNs in general work).

I'll close this issue right away. Thanks for the swift reply!
