### ISSUE TITLE
Doesn't work on Android 11 - Samsung device

### ISSUE THREAD

**Issue by roybeitner** [Genymobile/gnirehtet#346]
ERROR Main: Cannot start client: Command ...\adb.exe ["shell", "dumpsys", "package", "com.genymobile.gnirehtet"] failed: The system cannot find the file specified. (os error 2)

**Comment by rom1v** [comment]
Do you have `adb`?

What is the result of `adb devices`?

**Comment by roybeitner** [comment]
Looks like my adb environment variable path was incorrect. Fixed it and it works now! 💯
