### ISSUE TITLE
Gnirehtet doesn't work 

### ISSUE THREAD

**Issue by gingercookies** [Genymobile/gnirehtet#355]
Pls help me
![C__WINDOWS_system32_cmd exe 25_01_2021 10_59_21 CH](https://user-images.githubusercontent.com/77981365/105731059-9323de80-5f61-11eb-8165-67cd82767ece.png)
It just show that, there is no internet connection on my phone

**Comment by rom1v** [comment]
Which gnirehtet version?
A dialog should open the first time on the device.

**Comment by gingercookies** [comment]
> Which gnirehtet version?
> A dialog should open the first time on the device.

It's 2.5.0

**Comment by gingercookies** [comment]
And this happening after i type ./gnirehtet autostart in powershell

**Comment by rom1v** [comment]
Oh, `start` and `autostart` only start the client.

Try `./gnirehtet run` or `./gnirehtet autorun`.

(Yes, the gnirehtet command-line interface is pretty bad in term of UX.)

**Comment by gingercookies** [comment]
@rom1v  it's working now . Thanks
![image](https://user-images.githubusercontent.com/77981365/106162159-61598480-61ba-11eb-9a43-4f3cef7231d5.png)
