### ISSUE TITLE
Only few apps are working via gnirehtet

### ISSUE THREAD

**Issue by snbk97** [Genymobile/gnirehtet#36]
Whatsapp, Telegram and Facebook work.
Downloads with Flud (Torrent) works
but regular downloads/browsing doesn't work

OS : Android 7.1.2

**Comment by rom1v** [comment]
> but regular downloads/browsing doesn't work

What's your browser? It works both with Firefox and Chrome (or it should).

**Comment by snbk97** [comment]
Tried on both Chrome and Firefox as well as the AOSP browser
Only thing working is Facebook  app, Telegram app and Whatsapp
Can't even open Facebook on Chrome 😛 

![screenshot_144](https://user-images.githubusercontent.com/11523415/28150082-e27552be-67af-11e7-8c41-41347453ec8b.png)

**Comment by rom1v** [comment]
Does your network require a proxy?

It seems that even DNS requests cannot be sent from your computer to 8.8.8.8 (it keeps retrying).

**Comment by snbk97** [comment]
I think that might be case.

**Comment by rom1v** [comment]
Then, see this comment: https://github.com/Genymobile/gnirehtet/issues/35#issuecomment-310173049

**Comment by rom1v** [comment]
Since the problem seems related to your proxy configuration, I'm closing the issue.

Feel free to reopen if you think there is an issue in gnirehtet.
