### ISSUE TITLE
help me please! my cell phone is a redmi note 5 and is giving this error.

### ISSUE THREAD

**Issue by eutheus** [Genymobile/gnirehtet#367]
2021-03-07 09:18:53.461 I Gnirehtet: Checking gnirehtet client...
2021-03-07 09:18:53.461 I Gnirehtet: Starting relay server on port 31416...
2021-03-07 09:18:53.913 I Relay: Relay server started
2021-03-07 09:18:58.718 I Gnirehtet: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnireht
et/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnir
ehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } fro
m null (pid=26466, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymo
bile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActiv
ity } from null (pid=26466, uid=2000) requires android.permission.WRITE_SECURE_S
ETTINGS

**Comment by rom1v** [comment]
#5
