### ISSUE TITLE
gnirehtet cannot read error

### ISSUE THREAD

**Issue by nando2938** [Genymobile/gnirehtet#38]
I was using gnirehtet without problem, but people of the sistem area modified the IP of my PC and now it gives me error, it says : “cannot read”.

2017-08-24 18:20:49.926 I UDPConnection: UDP 10.0.0.2:48184 -> 8.8.8.8:53 Open
2017-08-24 18:20:52.431 E TCPConnection: TCP 10.0.0.2:39669 -> 157.240.12.36:443 Cannot read                                                           

The apps it not working (whatsapp, messenger, facebook, etc.)
How do I solve the problem?

**Comment by rom1v** [comment]
Do you now require a proxy?
https://github.com/Genymobile/gnirehtet/issues/27#issuecomment-296404498

**Comment by nando2938** [comment]
Use a proxy server for your LAN,  is enable
Bypass proxy server for local addresses, is enable too

**Comment by nando2938** [comment]
It's crazy what happens. The app whatsapp and twitter works ok but facebook, Instagram and messenger are not working now.
Before the change of the IP all the mentioned apps was working ok
Now and before requires a proxy to navigate
I am disoriented I don't know what to do to solve the problem

**Comment by godofrayer** [comment]
"facebook, Instagram and messenger are not working now." They block them.

**Comment by nando2938** [comment]
"facebook, Instagram and messenger are not working now. They block them."
Who is blocking them?
How can they block the apps on my cell phone?
