### ISSUE TITLE
Google Store Unavailable

### ISSUE THREAD

**Issue by send495** [Genymobile/gnirehtet#39]
Cannot install or update apps from Google Store any more.  Gnirehtet used to work fine with Google Store under Andriod 6.0.1 (marshmallow). Since installation of Android 7.0 (nougat) connection with Google Store is not working. Message on phone when tap on Google Store: "No Internet connection. Make sure that Wi-Fi or cellular mobile data is turned on, then try again".  
![googlestoreunavailable](https://user-images.githubusercontent.com/31666437/30075250-55413512-9242-11e7-8f13-5e24eb584f1f.png)
Other Internet access are fine. I can browse with Chrome no problem. That is working fine. My only alternative for now on Google Store is free Wi-Fi.

**Comment by rom1v** [comment]
It seems that some versions of the Play Store check for Wi-Fi or mobile data to be available, but not any kind of connectivity.

A priori, _gnirehtet_ can do nothing about it. See https://github.com/Genymobile/gnirehtet/issues/37.

**Comment by qdeeds76** [comment]
I get aggravated every time I come here hoping for any insight whatsoever to get play store to work.

**Comment by rom1v** [comment]
You should report the problem to the Google Play Store project. :trollface: 

Or just connect by Wifi to any access point (even if it does not have internet access), so that the Play Store thinks there is connectivity (and the connection will pass through gnirehtet).

**Comment by qdeeds76** [comment]
Thank you for your help.   I need to apologize for having been needlessly bitchy and aggravated.

I believe you are right.   I am a little perterbed that google would naively sabatage all their apps in this manner,  I mean its gonna be more than likely using bluetooth,  data,  or wifi,  but still.... I have no freaking idea how linux or bsd nerds managed to write network apps without a few Google geniuses on board for all those dark years.   I am not a coder and I'll quit withhe negativity.

I set my LG v20, the nicest and most expensive phone I've ever owned,  on the hood of my car to go  run inside my hotel room and grab something at the bequest of that freeloading peckerhead and he surely noticed,  as he was somewhat shrewd and conniving for a peckerhead.   But the result was fairly cool,  so I can't hate him for this.   As I took a curve at 50 mph I heard the overly familiar ding of my phone's back and battery being flung from their casing,  couldnt turn around for a mile but it survived,  by golly.  It looked much cooler totally smashed up and everything worked but wifi and bluetooth.  US cellular had gratuously chosen that week to go all 47 chromosomes on me so I had no network,  till I found gnirehtet and I apologize again for my negativity,  as it saved my v20's life.

Sent from MailDroid<https://goo.gl/ODgwBb>

-----Original Message-----

**Comment by rom1v** [comment]
> I need to apologize

:+1: :wink: (ref: https://github.com/Genymobile/gnirehtet/issues/37#issuecomment-415689347)

> I am a little perterbed that google would naively sabatage all their apps in this manner

I think they just did not consider the use case. They probably just tried to detect possible errors in advance.

According to answers in #37, the issue depends on the Google Play version.

**Comment by qdeeds76** [comment]
I helieve that has been the case.   And it just may be a delusion on my part but I've been noticing some refinement in several of their interfaces,  and I want to believe that they just implemented this chicanery basically across the board as Google Play Games was updated to do the same,  and I have the feeling the error message it says in telling you there is no network is different from what the play store's was,  but now the play store and all google apps say this same new no-nonsense "Not even bothering starting this app as there is no network,  duh,  and I am not gonna even try checking,  kay? " thing,  which kinda ties to my consternation as all the games I had been using my v20 for are now pooping out cause google apps feel logic trumps reality.   Its all good.   Im trying to figure out how to trick this particuarly obnoxious logic,  can't be too hard if its not really testing internet by you know,  testing internet?    Lol

Sent from MailDroid<https://goo.gl/ODgwBb>

-----Original Message-----

**Comment by JERINPWILSON** [comment]
guys i tried gnirehtet. the connection was established but could not access internet. so i thought it was because i didn't use proxy so i tried #4 .now after removing i cant use internet in any google related app such as play store ,insta, or chrome. i tried network resetting on phone but nothing changed.  i am a noob experimenting on ubuntu. plz help @rom1v

**Comment by rom1v** [comment]
> the connection was established but could not access internet

What was printed in the console?

> now after removing

After removing what? Did you disconnect gnirehtet (on the device, in the notification panel, you can "stop gnirehtet"?
