### ISSUE TITLE
Messaging apps not working on gnirehtet

### ISSUE THREAD

**Issue by njmulsqb** [Genymobile/gnirehtet#393]
Hi,

I am using gnirehtet on my Huawei android 8.0, browser is working fine on the mobile but messaging apps like Telegram, Signal etc are not working along with some other apps.

**Comment by rom1v** [comment]
Just for testing, do these apps work if you are connected to a wifi network while gnirehtet is running? (if they do, they will still use gnirehtet and wifi should not be used)

Some apps decide to disable any connections if there is no wifi or mobile network connectivity.

**Comment by najum98** [comment]
> Just for testing, do these apps work if you are connected to a wifi network while gnirehtet is running? (if they do, they will still use gnirehtet and wifi should not be used)
> 
> Some apps decide to disable any connections if there is no wifi or mobile network connectivity.

I am using gnirehtet because I cant use wifi here so cant test this. But these apps do work fine on my laptop on the same wifi so there is no such restriction on wifi

**Comment by rom1v** [comment]
> I am using gnirehtet because I cant use wifi here so cant test this.

OK, if you could test somewhere it will help to know if this is the cause of the problem.

> But these apps do work fine on my laptop on the same wifi so there is no such restriction on wifi

Yes, but if your device is connected to a wifi network and gnirehtet is running, then the wifi network will not be used at all (only gnirehtet wlil be used), but it will just make some apps which explicitly test if wifi is connected.

**Comment by najum98** [comment]
Alright,

I have enabled the wifi with gnirehtet running. Now the apps are working fine.

I have one question, what if I just enable the wifi and not get connected to some wifi router, will this work then too?

**Comment by rom1v** [comment]
Unfortunately, I think you have to be connected to some access point (even an access point without any internet access).

**Comment by najum98** [comment]
Alright, it means that if some apps checks for wifi and I don't have any access point to connect to, then gnurehtet wont work. Right?

**Comment by rom1v** [comment]
Gnirehtet works (it still relays all connections), but the apps themselves will just not send anything.

**Comment by najum98** [comment]
Okay. Thank you for this awesome tool. Consider this issue solved.
