### ISSUE TITLE
can't install gnirehtet.apk on android 10 

### ISSUE THREAD

**Issue by ZeinabBahaa** [Genymobile/gnirehtet#398]
I transferred gnirehtet.apk file to my android 10 phone 
But I get an error when trying to install app

**Comment by rom1v** [comment]
> But I get an error

Which error?

**Comment by ZeinabBahaa** [comment]
> 
> 
> > But I get an error
> 
> Which error?

Thanks, the problem has been resolved
The error was on my phone
