### ISSUE TITLE
gnirehtet can not run as service in Android

### ISSUE THREAD

**Issue by Biswa96** [Genymobile/gnirehtet#40]
After running the relay server with `javaw -jar relay.jar`, I ran the command `adb -s %serial% shell am startservice -a com.genymobile.gnirehtet.START --esa dsnServers 8.8.8.8` in command prompt. But that gave some error.

>Starting service: Intent { act=com.genymobile.gnirehtet.START (has extras) }
>Error: Requires permission android.permission.WRITE_SECURE_SETTINGS

My smartphone is Redmi 3S with MIUI8 and Android 6.0.1. What is that error? How do I solve that?

**Comment by rom1v** [comment]
See https://github.com/Genymobile/gnirehtet/issues/5.

**Comment by Biswa96** [comment]
I can enable USB Debugging in Developer Mode. But enabling USB Debugging Security Settings requires to create MI account. I do not want to create that account. Here is the [screenshot](https://user-images.githubusercontent.com/31443074/30251944-584f098a-9659-11e7-8cf4-45a8edb8d58d.png) of android developer settings.

* Isn't there a way to reverse tethering just with `adb.exe -s %serial% reverse tcp:port tcp:port` command and with making a VPN in Android client?

**Comment by rom1v** [comment]
> But enabling USB Debugging Security Settings requires to create MI account.

😕 

> Isn't there a way to reverse tethering just with `adb.exe -s %serial% reverse tcp:port tcp:port` command and with making a VPN in Android client?

The _gnirehtet_ Android client is intended to be controlled from the computer only, there is no UI.

That's unfortunate that some vendors change some default Android behavior and prevent the settings to be changed without registering an account with them. Currently, I have no good solution.

If you know how to build, as a workaround, you can just remove this `android:permission` field in `AndroidManifest.xml`.

**Comment by Biswa96** [comment]
I want to reverse tethering with only adb.exe command line tool and not with reply.jar and not with .APK. Is that possible?

**Comment by rom1v** [comment]
> I want to reverse tethering with only adb.exe command line tool and not with reply.jar and not with .APK. Is that possible?

No, that's not possible (otherwise, _gniretet_ would be useless).

`reverse` in `adb reverse` is for _reverse port forwarding_, not _reverse tethering_.

**Comment by Biswa96** [comment]
As you say, I remove the `android:permission="android.permission.WRITE_SECURE_SETTINGS"` line from **AndroidManifest.xml** file. And now I am fully able to reverse tethering in my Redmi 3S. My problem is solved. Thank you. 😍

You should add this tweak in readme file. But I edit that with Apk Editor Pro app. How does this tweak solve my issue? How can I edit that xml file in PC? Notepad++ does not open yah xml file as text!

**Comment by rom1v** [comment]
Cool :+1:

> How does this tweak solve my issue?

_Gnirehtet_ requests a `WRITE_SECURE_SETTINGS` permission for reasons explained in https://github.com/Genymobile/gnirehtet/commit/e7b84076a05effebf4aa2f47c9ad8ffff4fda382.

Your vendor-version of Android refuses to grant it (without enabling some settings that requires to register an account with them), so this tweak just make _Gnirehtet_ not requesting the permission.

> How can I edit that xml file in PC? How can I edit that xml file in PC?

If you download the [raw source file](https://raw.githubusercontent.com/Genymobile/gnirehtet/736aff8680ab26c0578d2d77886df22959bfc057/app/src/main/AndroidManifest.xml), it should. If you tried to open the APK as a zip, yes, `AndroidManifest.xml` is in some [binary XML format](https://stackoverflow.com/questions/2097813/how-to-parse-the-androidmanifest-xml-file-inside-an-apk-package).

**Comment by Biswa96** [comment]
I have more to contribute. I ran your app without the whole Android SDK. I use just the ADB tool.

For Java, I use only the JRE, downloaded as zip format, add the javaw.exe path in that .CMD file.

**Comment by Biswa96** [comment]
Is there any automatic build process like Appveyor, Travis etc. where I can build this project. I don't want to setup Android and rust environment in my PC. And I've to edit the manifest file for my Redmi 3S.

**Comment by timeakesmarky** [comment]
> > But enabling USB Debugging Security Settings requires to create MI account.
> 
> 😕
> 

This can be bypassed if a device has root.
First, run the following commands:
`adb shell`
`su`
`setprop persist.security.adbinstall 1`

If you also want to enable "USB debugging (Security settings)", for granting permissions, simulating UI input, etc. via ADB, run the following command too:
`setprop persist.security.adbinput 1`

Next, we need to edit the file,
`/data/data/com.miui.securitycenter/shared_prefs/remote_provider_preferences.xml`

Add the following line to the XML file (with all the other ones, before the closing </map> tag, or change it to true if the line is already there):
`<boolean name="security_adb_install_enable" value="true" />`

Reboot your device.

**Comment by Biswa96** [comment]
> This can be bypassed if a device has root.

Anything can be done with root access in any Android device or any PC 😎 Also the main feature of gnirehtet is that it does not require any root access.

**Comment by timeakesmarky** [comment]
Even if you root, it'll still ask you to sign in to enable debugging.
Lots of people, even with root are struggling to enable debugging without creating an account. Not everyone knows everything. It's a tip for root users who don't know about it. :)

**Comment by XylverXVI** [comment]
> As you say, I remove the `android:permission="android.permission.WRITE_SECURE_SETTINGS"` line from **AndroidManifest.xml** file. And now I am fully able to reverse tethering in my Redmi 3S. My problem is solved. Thank you. 😍
> 
> You should add this tweak in readme file. But I edit that with Apk Editor Pro app. How does this tweak solve my issue? How can I edit that xml file in PC? Notepad++ does not open that xml file as text!

Sir can you give the build that you use for Your Redmi 3S? I am still a beginner so I cannot understand well what to do. And I can only do it on computer shops which I have access for about 1 hour. I want to use your build for my realme 5. I would really appreciate it sir.

**Comment by Biswa96** [comment]
@XylverXVI Added the APK only https://github.com/Biswa96/gnirehtet-miui/releases. Download the server side binary from gnirehtet release page.

**Comment by XylverXVI** [comment]
Many thanks Sir!

**Comment by Biswa96** [comment]
I am not the original developer. There is no restriction from my side. @rom1v may help.

**Comment by adityakaushal5nov** [comment]
@Biswa96 the link to your apk is failing to install.
I am running into the same problem where i require to sign to MI Account to give access which i can't since the phone is not reading any SIM or connecting to any wifi.

the problem remains.
Can anyone provide an apk with the manifest file modified? 
Setting up android studio is not feasible for me right now!

**Comment by adityakaushal5nov** [comment]
@Biswa96 Thanks for the help :)

**Comment by tvinki899** [comment]
@Biswa96 ty bro! i fucking trying fix this problem all day yesterday

**Comment by Hevin007** [comment]
> 

Thanks, this answer fix my problem to enable "USB debugging (Security settings)"
