### ISSUE TITLE
Access server on the device from computer

### ISSUE THREAD

**Issue by lewisxy** [Genymobile/gnirehtet#405]
I would like to have my computer supplying Internet access to an android device while starting a private server (using another app) from the android device that is only accessible from the computer. The first step works out of the box, but the second step does not. On the android device, my app that starts the server shows that the IP was `10.0.0.2`, and ask me to connect with `http://10.0.0.2:8080`. However, when I enter this to my browser in computer, it doesn't work. It seems like I cannot access the android device using this IP from the computer. Are there anyway to configure this?

**Comment by rom1v** [comment]
No, gnirehtet could not provide this feature: the device and computer are not on the same "network". Only connections initiated from the device are forwarded.

But you could just forward a specific port:

```
adb forward tcp:1234 tcp:8080
```
Then connect to http://localhost:1234 from the computer.

**Comment by lewisxy** [comment]
I see, it's working. Thanks
