### ISSUE TITLE
Might have broken phone's OS.

### ISSUE THREAD

**Issue by TroublingFoe** [Genymobile/gnirehtet#409]
Used it on my P8 Lite for about three weeks, and now my phone is in a boot loop. Rebooting every 2 minutes. It stopped doing this early this morning when I had stopped using Gnirehtet, then the second I tried again, the issue returned and is currently happening.

**Comment by rom1v** [comment]
Gnirehtet only uses public Android APIs, like any Android app could do.

**Comment by TroublingFoe** [comment]
It was not gnirehtet after all. Thank you.
