### ISSUE TITLE
Change TCP port in both relay and client

### ISSUE THREAD

**Issue by Biswa96** [Genymobile/gnirehtet#41]
Both client and server connect to each other with `TCP port 31416`. I find the port in two .java files

`relay/src/main/java/com/genymobile/relay/Relay.java`
`app/src/main/java/com/genymobile/gnirehtet/RelayTunnel.java`

* The code:: `private static final int DEFAULT_PORT = 31416;`

Questions:: 
* Can I change that port number just by editing? 
* Should I do in in both .java files? 
* Can the port be set to any random port with `adb reverse` command?

**Comment by rom1v** [comment]
There are 2 ports constants (for the tunnel and for the server), both defined as `31416` in 3 different places:
 - the [client](https://github.com/Genymobile/gnirehtet/blob/736aff8680ab26c0578d2d77886df22959bfc057/app/src/main/java/com/genymobile/gnirehtet/RelayTunnel.java#L33) (the tunnel port),
 - the tunnel in the [bash](https://github.com/Genymobile/gnirehtet/blob/736aff8680ab26c0578d2d77886df22959bfc057/gnirehtet#L134) and [cmd](https://github.com/Genymobile/gnirehtet/blob/736aff8680ab26c0578d2d77886df22959bfc057/gnirehtet.cmd#L129) scripts in the current version (both ports),
 - the [server](https://github.com/Genymobile/gnirehtet/blob/736aff8680ab26c0578d2d77886df22959bfc057/relay/src/main/java/com/genymobile/relay/Relay.java#L26) (the server port).

> Can I change that port number just by editing?

Yes, you can.

> Should I do in in both .java files?

If you want to change the tunnel port, edit the client and the tunnel script.
If you want to change the server port, edit the tunnel script and the server.

> Can the port be set to any random port with adb reverse command?

Yes, they just need to be unused and to match (the client must connect to the tunnel port, the tunnel must connect to the server port).

By curiosity, why do you need to change them (I'm interested in the use case)?

**Comment by Biswa96** [comment]
Please forgive me if I violate any T&C.
I found another java application for Android in Google Play named "Reverse Tethering NoRoot". Here are the [Server](https://www.partition-tool.com/easeus-partition-manager/help/moving-parition.htm) and [Client](https://play.google.com/store/apps/details?id=com.floriandraschbacher.reversetethering.free&hl=en). In that app one has not set TCP/UDP port, it is selected automatically with `adb fork-server server` and `adb reverse` process.
Hence I am trying them in your project.

**Comment by rom1v** [comment]
> In that app one has not set TCP/UDP port, it is selected automatically with `adb fork-server server` and `adb reverse` process.

What do you mean? How do you know that it is "selected automatically"?
And what's the benefit here?

What are you trying to do, could you give more context, please?

_Your "Server" link points to  "partition-tool", I think this is an error._

```
 reverse [--no-rebind] REMOTE LOCAL
     reverse socket connection using:
       tcp:<port> (<remote> may be "tcp:0" to pick any open port)
       localabstract:<unix domain socket name>
       localreserved:<unix domain socket name>
       localfilesystem:<unix domain socket name>
```

**Comment by Biswa96** [comment]
I find a similarity inside GnirehtetService.java. In this file, you set Google DNS if user does not configure other DNS IP. With same analogy, you may also configure TCP Port number to be set by user.

**Comment by rom1v** [comment]
> With same analogy, you may also configure TCP Port number as a variable and to be set by user.

Yes, this is technically possible.

But could you explain your use case? Why do you need to change that port?

> By the way, it would be helpful if you add a VPN network diagram (in readme file) where you mentioned the Port-Restricted NAT.

What diagram would you need?

I guess you already read [`DEVELOP.md`](https://github.com/Genymobile/gnirehtet/blob/master/DEVELOP.md)…

**Comment by frantisekhanzlikbl** [comment]
Since #165 was closed in favour of this issue, should this not be reopened?
I feel like blocking BOINC is quite a serious issue, and it's been over a year since the original issue was closed.

**Comment by rom1v** [comment]
You could change the port:

    gnirehtet run -p 12345
