### ISSUE TITLE
USB hub and otg cable on gniretet

### ISSUE THREAD

**Issue by Guilherme7N** [Genymobile/gnirehtet#424]
Hi!

Is it possible for this program to work with an otg cable combined with a usb hub? I would need this to use the program and connect my mouse and keyboard to my phone.

**Comment by GameDevIvan** [comment]
I tried this out for you and it didn't work. 

I've connected an OTG adapter to a Samsung S6 and connected a USB C cable to that OTG adapter, which I've plugged into a USB C socket on a Lenovo Carbon X1. No connection (doesn't even charge).

Maybe try this out with an USB A-to-A cable.

**Comment by rom1v** [comment]
FYI, `scrcpy` has an `--otg` feature: https://github.com/Genymobile/scrcpy#otg
