### ISSUE TITLE
Cannot write: [PermissionDenied] Operation not permitted (os error 1)

### ISSUE THREAD

**Issue by ureru** [Genymobile/gnirehtet#429]
There is an old issue for this but for some reason it's not being bumped even when I post in it so I'm not sure I'll be able to get any help that way:
https://github.com/Genymobile/gnirehtet/issues/362#issuecomment-1032295564
You can find the issue there.

I suspect this is just because of having a vpn. (But I have no compelling evidence)
If so, just implement an option to let me forward tun0 to the phone instead of eth0, and that should fix it.

**Comment by rom1v** [comment]
Duplicate.

**Comment by ureru** [comment]
It's an intentional duplicate because for some reason I couldn't bump the old one so I thought it would never be noticed.
