### ISSUE TITLE
Long-lived connection uploading lot of data dropping

### ISSUE THREAD

**Issue by guiniol** [Genymobile/gnirehtet#43]
Trying to do a speedtest, I noticed the upload was rather low. At the same time there were a lot of errors like these:
```
2017-09-25 16:25:16.323 INFO TcpConnection: 10.0.0.2:58359 -> 84.39.33.42:8080 Open
2017-09-25 16:25:16.323 WARN TcpConnection: 10.0.0.2:58359 -> 84.39.33.42:8080 Unexpected first packet 3509394381; acking 1239190467; flags=17
2017-09-25 16:25:16.323 INFO TcpConnection: 10.0.0.2:58359 -> 84.39.33.42:8080 Close
```

Trying to scp a large file, the transfer never started as seemingly every single `TcpConnection` is closed with an `Unexpected first packet`.
Using nc instead, the transfer starts and is rather fast until nc says `connection reset by peer` which happens at the same time as an `Unexpected first packet`.

**Comment by rom1v** [comment]
The errors `Unexpected first packet 3509394381; acking 1239190467; flags=17` are not a big deal, unless the very same line with the same numbers keeps printing. It's probably an old open connection before your restarted the gnirehtet client, while the other TCP peer was not aware of.

Comparing a simple transfer through _netcat_ with and without _gnirehtet_, I don't get such a huge difference. What to you use to upload a file? Is it over HTTP?

Here is my test, using TCP directly. On the computer, I started:

    nc -l -p 1234 | pv > /dev/null

Without gnirehtet:

    adb reverse tcp:1234 tcp:1234
    adb shell "< /sdcard/somefile nc 127.0.0.1 1234"

The bitrate is ~4.9Mib/s.

With gnirehtet:

    ./gnirehtet run
    adb shell "< /sdcard/somefile nc 10.0.2.2 1234"

The bitrate is ~4.2Mib/s.

**Comment by guiniol** [comment]
I did exactly that: `nc -l -p 1234 | pv > /dev/null`
And I don't think there's a large difference between direct and through gnirehtet. The problem is that the connection gets dropped after a while so that the transfer never finishes (I was transfering an 800MB iso). I thought the `Unexpected first packet` was a clue to the connection dropping.

I changed the title of the issue to reflect the actual problem: when uploading a lot of data, the connection drops at some point. This doesn't seem to happen when downloading data.

**Comment by rom1v** [comment]
> The problem is that the connection gets dropped after a while so that the transfer never finishes (I was transfering an 800MB iso).

In fact, IMO the transfer is complete (there is nothing more to upload), but _netcat_ does not return.

Try everything from your computer:

    nc -l -p 1234 | pv > /dev/null
    nc localhost 1234 < file.iso

The commands never return, even after the transfer is complete.

**Comment by guiniol** [comment]
The connection does drop before the file finishes transferring. See attached screenshots.
On the phone:
![phone](https://user-images.githubusercontent.com/3483433/30849094-7ec5fb38-a2a1-11e7-8b5e-f4850be41a08.png)
On the computer:
![computer](https://user-images.githubusercontent.com/3483433/30849102-87c04202-a2a1-11e7-8f2b-50351fa4ee79.png)

The file is 867M so it hasn't been all transferred.

**Comment by rom1v** [comment]
OK, thank you for the details.

It still seems ok for me, a RST may happen, and _netcat_ just exits on RST.

By the way, what is 10.8.0.245? Don't you use it over the `adb reverse` tunnel?

**Comment by guiniol** [comment]
`10.8.0.245` is my computer's ip. So this is over the gnirehtet tunnel.

The thing is, there shouldn't be a RST. When I do it only with `adb reverse`, there are no RST and the transfer completes.

**Comment by rom1v** [comment]
> `10.8.0.245` is my computer's ip. So this is over the gnirehtet tunnel.

OK. You can use `10.0.2.2` to target the host `127.0.0.1` if you want.

I think I reproduced the issue with a Nexus 5X.

In server logs, I see that the client gets disconnected with no reason (which breaks the transfer) then reconnected. Do you have the same problem?

    2017-09-26 10:32:51.567 INFO TunnelServer: Client #0 disconnected
    2017-09-26 10:32:56.572 INFO TunnelServer: Client #1 connected

Could you reproduce the same problem with the Java version of Gnirehtet?

**Comment by guiniol** [comment]
Indeed, I do get a disconnection/reconnection. I didn't see it because there are a bunch of INFO/WARN messages as connections are reestablished.

With the java version, I was able to do three full transfers without a hitch. So I would say it works and the bug is in the rust version.

**Comment by rom1v** [comment]
👍 

Then it's fixed: https://github.com/Genymobile/gnirehtet/commit/69248391414ff1073dd0142c98e597795274d6c7

**Comment by rom1v** [comment]
Here is a binary with the fix: [gnirehtet](https://tmp.rom1v.com/gnirehtet/issue43/gnirehtet).
_(sha256: ef2e8019423b269731e833aee114c36da669eb7d4d53eef51ec1b740aefeea18)_

**Comment by guiniol** [comment]
Three transfers. 0 problem!
