### ISSUE TITLE
Any way to access filesystem of reverse-tethered device from PC?

### ISSUE THREAD

**Issue by Friptick** [Genymobile/gnirehtet#446]
This project is great, thanks for your work.

Does the Android device, when reverse-tethered, have an IP address?

Is there any way (workarounds accepted) to access the Android device's filesystem (via SSHD or similar) from the PC?

**Comment by rom1v** [comment]
> Does the Android device, when reverse-tethered, have an IP address?

Nope.

> there any way (workarounds accepted) to access the Android device's filesystem (via SSHD or similar) from the PC?

mtp? maybe adbfs (don't know if this still works)

**Comment by Friptick** [comment]
Thanks, that's helpful.

**Comment by NA0341** [comment]
@rom1v said:
> > Does the Android device, when reverse-tethered, have an IP address?
> 
> Nope.

I created a Feature Request regarding this topic: #554
