### ISSUE TITLE
internet only in browser and few few apps like youtube and play store on Redmi 9t miui 12.5

### ISSUE THREAD

**Issue by elswerky** [Genymobile/gnirehtet#474]
hello i tested gnirehtet in many devices and working as expected even some of these devices are xiaomi devices with miui 12.5 and miui 13

but when i tried to make it run on my redmi 9t miui 12.5 ,, it can only provide internet in browsers and very few noticed apps like youtube 

even in play store it can provide internet but can't download any app 

also tested it in apps like facebook lite ,, telegram ,, plus messenger and not working in all those and other apps 

although such apps like fb lite and plus messenger was working on other devices with gnirehtet 

if any one can help me 
thanks

**Comment by rom1v** [comment]
Hi,

Please do not open multiple issues for the same problem, but post your message in your previous issue (#473) instead.

For the problem itself, I have not idea :disappointed:
