### ISSUE TITLE
`gnirehtet relay` will IO error if binary built with Rust 1.64.0+

### ISSUE THREAD

**Issue by cho-m** [Genymobile/gnirehtet#475]
In Homebrew, we currently need to rebuild `gnirehtet` due to an issue with our Linux pre-built binary, but all recent rebuild attempts result in a binary that doesn't work correctly.

Doing some debugging locally, I noticed that the binary built with Rust 1.64.0 or 1.65.0 will error:
```console
❯ gnirehtet relay
2022-12-01 18:27:56.744 INFO Main: Starting relay server on port 31416...
2022-12-01 18:27:56.745 ERROR Main: Execution error: IO error: Address family not supported by protocol family (os error 47)
```

Experimenting with a few different versions of Rust, I found that the last version that didn't error was 1.63.0:
```console
❯ gnirehtet relay
2022-12-01 18:34:53.803 INFO Main: Starting relay server on port 31416...
2022-12-01 18:34:53.804 INFO Relay: Relay server started
```

I assume `gnirehtet` is not compatible with changes introduced with new Rust versions.

**Comment by Quantenzitrone** [comment]
i have this on NixOS too
works with rust 1.60 (gnirehted from Nixpkgs 22.05)
doesn't work with rust 1.65 (from unstable)

**Comment by rom1v** [comment]
I can reproduce:

```
2022-12-26 14:13:55.287 ERROR Main: Execution error: IO error: Invalid argument (os error 22)
```

On this line: https://github.com/Genymobile/gnirehtet/blob/9ad9bc83d1a6e6c2c3e095985269ab98f5ee08ab/relay-rust/src/relay/tunnel_server.rs#L67

```rust
        let localhost = Ipv4Addr::new(127, 0, 0, 1).into();
        let addr = SocketAddr::new(localhost, port);
        let server = TcpListener::bind(&addr)?;
```

This is not expected to fail, a breaking change probably occurred in Rust 1.64.

To be investigated.

**Comment by rom1v** [comment]
Please confirm that it works with #478.

**Comment by chenrui333** [comment]
I can confirm it builds/runs fine with #478, tested out in my local against rust 1.66.0.
