### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by chenrui333** [Genymobile/gnirehtet#477]
👋 looks like the last commit was back in 2020, is this repo still being maintained? Thanks!!

relates to https://github.com/Homebrew/homebrew-core/pull/117139

**Comment by rom1v** [comment]
I have to admit that it is not actively maintained anymore (free time is limited, and I use that time to develop/maintain [scrcpy](https://github.com/Genymobile/scrcpy)).

However, the breaking build in Rust 1.64 should still be fixed.

**Comment by rom1v** [comment]
https://github.com/Genymobile/gnirehtet/commit/848a3caa3ed6f3ada7972db102eccedbfde5807a
