### ISSUE TITLE
IO error when using cargo 1.70.0 and gnirehtet v2.5

### ISSUE THREAD

**Issue by chris-est** [Genymobile/gnirehtet#499]
Hi,
building gnirehtet v2.5 using cargo 1.70.0 creates a binary but it can not start:
```
gnirehtet run
2023-07-09 10:23:35.128 INFO Main: Starting relay server on port 31416...
2023-07-09 10:23:35.128 INFO Main: Checking gnirehtet client...
2023-07-09 10:23:35.128 ERROR Main: Execution error: IO error: Invalid argument (os error 22)
```
When building gnirehtet git-master it works!

Could you please release a new version (2.5.1 / 2.6)? So we can update the package in the [AUR](https://aur.archlinux.org/packages/gnirehtet), thank you.

**Comment by rom1v** [comment]
Just for information, would a new tag 2.5.1 be sufficient, or do you absolutely need a new "release"?

**Comment by chris-est** [comment]
Would a tag create a new .tar.gz? Then yes.
We use the archived files, i.e. "https://github.com/Genymobile/gnirehtet/archive/refs/tags/v2.5.tar.gz" for our build.

**Comment by rom1v** [comment]
I made a new release, there were other fixes on master that were not released yet: https://github.com/Genymobile/gnirehtet/releases/tag/v2.5.1

**Comment by chris-est** [comment]
Thank you so much, appreciate it
