### ISSUE TITLE
version 2 for windows 32bit

### ISSUE THREAD

**Issue by anonggnona** [Genymobile/gnirehtet#50]
Im not able to run the application since its for 64 bit only. Is there any for 32bit? my windows is 32bit version.

im trying to reverse tethering my android version 7.1.1 using gnirehtet

**Comment by Biswa96** [comment]
Did you try the Java one? Why not you just upgrade PC to Windows 10
 64bit?

**Comment by anonggnona** [comment]
I tried the java one but its stuck in checking gnirehtet client.
I can't upgrade my OS since I have application that runs only in 32bit

**Comment by anonggnona** [comment]
I already enable the USB Debugging in my phone

**Comment by rom1v** [comment]
> I tried the java one but its stuck in checking gnirehtet client.

What is the result of `adb devices`?

> Is there any for 32bit?

No, but you can compile it yourself on your host (cf [`DEVELOP.md`](https://github.com/Genymobile/gnirehtet/blob/master/DEVELOP.md)).

In theory, you can also cross-compile, but I just tried from Linux 64 bits to Windows 32 bits, it failed during link, and I have no time to investigate.

Anyway, if the java version is "stuck in checking gnirehtet client", the rust one should have the same problem: your device is probably not detected by `adb`.

**Comment by anonggnona** [comment]
here's the result of adb devices
![image](https://user-images.githubusercontent.com/32918850/31759854-50ca2f46-b4e5-11e7-91ce-905daf1f9661.png)

i think it is detected by adb.
![image](https://user-images.githubusercontent.com/32918850/31759920-7d626bf4-b4e5-11e7-97fc-c139fa22bc8a.png)

**Comment by anonggnona** [comment]
and here is my screenshot also when im using the old version of gnirehtet 1.1.1
![image](https://user-images.githubusercontent.com/32918850/31760073-14ddd752-b4e6-11e7-847b-4c241f1a396c.png)

but when im using other android phone its successfully connected. is there an issue for nougat version?

**Comment by rom1v** [comment]
Use the java version v2.1, and execute `adb uninstall` before starting it. The version of the client installed on the device and the relay server are probably different.

**Comment by Biswa96** [comment]
@anonggnona Allow installation apps via USB in developer options in phone. 
Or alternatively send the .apk file through MTP mode with USB (or use Bluetooth) to your Android phone. Then allow installation of apps from unknown sources in seetings and install the .apk in normal way.

**Comment by bazir123** [comment]
sir please build 32 bit android sdk is 64bit my windows 32bit
thanks
