### ISSUE TITLE
Service not found --- Used to work before...

### ISSUE THREAD

**Issue by ulisesguerrero** [Genymobile/gnirehtet#54]
Today I was unable to browse, updated to 2.1 and still out of luck.

When trying to find the cause, by starting manually:
adb shell am startservice -a com.genymobile.gnirehtet.START

Error displayed is:
"Starting service: Intent { act=com.genymobile.gnirehtet.START }
Error: Not found; no service started."

The apk is installed properly, and server running on the PC.

**Comment by rom1v** [comment]
It seems you use an old version of the relay server and a newer version of the APK...

**Comment by rom1v** [comment]
Thank you for the report.

The command has changed in the last version, I forgot to [update](https://github.com/Genymobile/gnirehtet/commit/39ce10133bc59497d7340a74f8b1a34988125691) the README:

    adb shell am broadcast -a com.genymobile.gnirehtet.START -n com.genymobile.gnirehtet/.GnirehtetControlReceiver
