### ISSUE TITLE
Troubles with Samsung S22+

### ISSUE THREAD

**Issue by eyal-shabi** [Genymobile/gnirehtet#551]
Hi there,
I'm trying to use the app with Samsung S22+.
The Android phone can connect to the internet through a web browser, for example.
However, when trying to use Gmail or a 3rd party app (BIGVU), they don't seem to connect to the internet.
Any ideas?

**Comment by Stephen1994201527** [comment]
oh,it can be easily solved,as we all known,the app on our phone won't really check you internet connect ,they will only check your wifi or sim card connect,so you can open you mobile data first to cheat you app ,then close it when you use app,it will only use you a little mobile data,but will works.(tips: i am not an ENGLISH user (in fact ,I am a CHINESE),my ENGLISH is really poor ,don't mind it)

**Comment by NA0341** [comment]
Yes indeed. Just enable WiFi or Cellular (Mobile) Data to trick those applications.
Sometimes they start working after some time even if they didn't before. Even without WiFi or Mobile Data turned on.

This issue is resolved and can be closed.

**Comment by Stephen1994201527** [comment]
Yes,there also some strange things.As you may know, I come from China.In China, XIAOMI will use MIUI based on Android 14,but it won't meet that question.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
