### ISSUE TITLE
Does not start on realme 8 (RMX3241)

### ISSUE THREAD

**Issue by lordofscripts** [Genymobile/gnirehtet#556]
Phone: realme 8 5G
Android: 13
OpenGL: 2.1

Setup:

-  Developer Options are enabled. 
-  _enabled_ **USB debugging**. 
- Default **USB configuration**: _USB Thethering_.
- **Disable permission monitoring**: _enabled_.

At first I was getting a Java Exception about not being able to set something. I went to Developer Options | Apps and _enabled_ "**Disable permission monitoring**". After that the error disappeared.

However, SCRCPY still doesn't work. The first thing that happens after launching scrcpy is that my phone's screen goes black. And the errors I see are these:

```
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 7.6 MB/s (71200 bytes in 0.009s)
[server] INFO: Device: [realme] realme RMX3241 (Android 13)
WARN: Trilinear filtering disabled (OpenGL 3.0+ or ES 2.0+ required)
[server] INFO: Device screen turned off
WARN: Device disconnected
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  UCCI5T4D4PUW5DSW                device  RMX3241
INFO: Renderer: opengl
INFO: OpenGL version: 2.1 Mesa 20.3.5
```

But it doesn't launch anything, even after I take the phone, turn the screen on again and click on Allow authorization (to use debugging with that host).

**Update #1:**
I started `adb logcat` in another terminal window and it vomited a lot of stuff. Then it _stopped output_ **but** was _still running/active_.

Then I ran `scrcpy` in another terminal. It outputted the info above with the `WARN: device disconnected`. And following that both adb instances stopped.

**Comment by lordofscripts** [comment]
**Update #2**: Finally got it working!

It started to work by not using the GUI shortcut, and instead start the tool like this:

>  `scrcpy --max-size 1024 `

The log didn't show any error or exception hinting that though, but I decided to try it and it worked!.

**Comment by rom1v** [comment]
You reported the issue on the wrong repo (gnirehtet vs scrcpy).

Btw, you can also try with another encoder: https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder

**Comment by lordofscripts** [comment]
> You reported the issue on the wrong repo (gnirehtet vs scrcpy).
> 
> Btw, you can also try with another encoder: https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder

Any particular encoder you recommend other than the default? 

```
[server] INFO: Device: [realme] realme RMX3241 (Android 13)
[server] INFO: List of video encoders:
    --video-codec=h264 --video-encoder='c2.mtk.avc.encoder'
    --video-codec=h264 --video-encoder='OMX.MTK.VIDEO.ENCODER.AVC'
    --video-codec=h264 --video-encoder='c2.android.avc.encoder'
    --video-codec=h264 --video-encoder='OMX.google.h264.encoder'
    --video-codec=h265 --video-encoder='c2.mtk.hevc.encoder'
    --video-codec=h265 --video-encoder='OMX.MTK.VIDEO.ENCODER.HEVC'
    --video-codec=h265 --video-encoder='c2.android.hevc.encoder'
[server] INFO: List of audio encoders:
    --audio-codec=opus --audio-encoder='c2.android.opus.encoder'
    --audio-codec=aac --audio-encoder='c2.android.aac.encoder'
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
    --audio-codec=flac --audio-encoder='c2.android.flac.encoder'
    --audio-codec=flac --a
udio-encoder='OMX.google.flac.encoder'
```

And thanks for pointing me to the correct repository. I just reported my scrolling issue there.

**Comment by rom1v** [comment]
Just test them all to see if they have the same buggy behavior (not starting, but blocked without reporting an error).
