### ISSUE TITLE
strange issue with adaway

### ISSUE THREAD

**Issue by gilcu3** [Genymobile/gnirehtet#56]
I have a very strange issue with [adaway](https://github.com/AdAway/AdAway), which I recently began using. When I add some user-defined redirection host - address, gnirehtet stops working. If I erase it it works again. So my question is: is there any way to get logs from gnirehtet just to try to figure out what is happening?

**Comment by rom1v** [comment]
For the Android client, just compile a debug version:

    cd app/
    gradle assembleDebug

It will generate `build/outputs/apk/gnirehtet-debug.apk`.

To increase logs for the relay server, you have to recompile after changing [this](https://github.com/Genymobile/gnirehtet/blob/v2.1/relay-java/src/main/java/com/genymobile/gnirehtet/relay/Log.java#L40) for the Java version or [that](https://github.com/Genymobile/gnirehtet/blob/v2.1/relay-rust/src/logger.rs#L20) for the Rust version.

**Comment by gilcu3** [comment]
Nope the VPN symbol at least stays ok. In android it shows the notification "disconnected from the relay server", and in the computer it only shows:
```
2017-11-03 09:51:12.623 INFO Main: Checking gnirehtet client...
2017-11-03 09:51:12.790 INFO Main: Starting relay server...
2017-11-03 09:51:12.791 INFO Relay: Relay server started
2017-11-03 09:51:12.791 INFO Main: Starting client...
Starting service: Intent { act=com.genymobile.gnirehtet.START (has extras) }
```

**Comment by rom1v** [comment]
Gnirehtet connects to [127.0.0.1:31416](https://github.com/Genymobile/gnirehtet/blob/v2.1/app/src/main/java/com/genymobile/gnirehtet/RelayTunnel.java#L48).

Is there a possibility that you block this connection to the relay server?

**Comment by gilcu3** [comment]
I don't think so, as I'm only adding (supposedly) some host-addres to the hosts file. It must be something strange with adaway. I will try to debug after compiling as you said, then get to the adaway thread and ask there. thank you for your time, I will later come back here and post updates...

**Comment by gilcu3** [comment]
hey, this may be unrelated, but I just realized I was using rust version 2.0, then tried to use 2.1 (./gnirehtet reinstall; ./gnirehtet start) and it didn't work, as the vpn dialog never appeared on my nexus 5 lineage os 14.1. Reverted back to 2.0, and it works as before...

**Comment by rom1v** [comment]
Arf, you have the same problem as https://github.com/Genymobile/gnirehtet/issues/55, then…

**Comment by gilcu3** [comment]
Nope sorry, I deleted my previous comment, as somehow tried it again and worked, I'm certainly now on version rust 2.1 :) sorry about it

**Comment by gilcu3** [comment]
Well, just tried my compiled debug version, and then the release version, rust 2.1, and everything is working fine. It seems it was a problem related to rust version 2.0 which I had, thanks for your time, I'm closing this :)

**Comment by rom1v** [comment]
Probably because you had the 2.0 Android app and 2.1 relay server, they are incompatible (the new version use broadcasts instead of service intents to support Android O).
