### ISSUE TITLE
Windows 11 Error

### ISSUE THREAD

**Issue by cymansplayground** [Genymobile/gnirehtet#569]
Just installed Windows 11 and was trying to use the same software (1:1) as I used on my Windows 10 PC (which worked). Now I get the following error:

`ERROR Main: Cannot start on device 35b4f01c0005: Command adb ["-s", "35b4f01c0005", "install", "-r", "gnirehtet.apk"] returned with value 1`

**Comment by rom1v** [comment]
Is adb installed / copied in the same directory as gnirehtet?

**Comment by cymansplayground** [comment]
I think everything it needs is there (in the same folder), or is something else required?

<img width="143" alt="image" src="https://github.com/user-attachments/assets/a5436d74-e0aa-49e1-a37e-b408a6318158">

**Comment by rom1v** [comment]
OK, then open a terminal in that directory, and execute:

```
adb -s 35b4f01c0005 install -r gnirehtet.apk
```

You will get the error message.

**Comment by cymansplayground** [comment]
Thanks. Windows does not recognize `adb` as an executable:

<img width="854" alt="image" src="https://github.com/user-attachments/assets/1854b2ca-db98-4714-a17d-d1425b0da636">

**Comment by rom1v** [comment]
Because you are in powershell, you must use `.\adb.exe` instead of `adb` here.

**Comment by cymansplayground** [comment]
OK, now I think I got the error message you meant:

`PS M:\Software\Standalone\USB Internet for Android> .\adb -s 35b4f01c0005 install -r gnirehtet.apk
adb: failed to install gnirehtet.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]`

**Comment by rom1v** [comment]
You try to install an older version than the one installed on your device.

Uninstall the newer version first:

```
adb uninstall com.genymobile.gnirehtet
```

**Comment by cymansplayground** [comment]
OK, the uninstall worked, but the install still failes:

<img width="763" alt="image" src="https://github.com/user-attachments/assets/79573fa5-ef1c-4066-8f52-5d3a1c5ee7ca">

**Comment by cymansplayground** [comment]
I downloaded the latest version and tried again, now it works! 😅
