### ISSUE TITLE
stderr

### ISSUE THREAD

**Issue by theprogrammer67** [Genymobile/gnirehtet#62]
why do not you use stderr?
I need a description of the error.
I can add to the code (line 2):
```
                             error! (target: TAG, "Execution error: {}", err);
                             eprintln! ("{} Execution error: {}", TAG, err); // STDERR
                             exit (3);
```
?
Or are there other solutions?

**Comment by rom1v** [comment]
You're absolutely right. Fixed by https://github.com/Genymobile/gnirehtet/commit/c13d5f984dbbc2d5d5f77a5c0e016bcff090af3a.
