### ISSUE TITLE
The Android client does not start

### ISSUE THREAD

**Issue by theprogrammer67** [Genymobile/gnirehtet#65]
The Android client does not start. No notifications on the phone screen
Android version - 6 and 7
Can I run it manually?

> 2017-12-06 15:35:24.367 INFO Main: Checking gnirehtet client...
> 2017-12-06 15:35:24.493 INFO Main: Starting relay server...
> 2017-12-06 15:35:24.493 INFO Main: Starting client...
> 2017-12-06 15:35:24.496 INFO Relay: Relay server started
> Broadcasting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver }
> Broadcast completed: result=0

**Comment by rom1v** [comment]
What is the result of:
    adb shell dumpsys package com.genymobile.gnirehtet | grep version
?

What if you `adb reinstall`?

**Comment by theprogrammer67** [comment]
```
    versionCode=4 targetSdk=26
    versionName=2.1
```

**Comment by theprogrammer67** [comment]
> What if you adb reinstall?
I did not understand (

**Comment by theprogrammer67** [comment]
with adb is not installed. Installed manually. Perhaps that's why it does not start?

```
2017-12-06 16:10:43.547 INFO Main: Installing gnirehtet client...
gnirehtet.apk: 1 file pushed. 0.5 MB/s (20616 bytes in 0.038s)
        pkg: /data/local/tmp/gnirehtet.apk
Failure [INSTALL_CANCELED_BY_USER]
```

**Comment by rom1v** [comment]
Sorry, I meant: what if you `gnirehtet reinstall`? :)

**Comment by theprogrammer67** [comment]
I think the reason is this

**Comment by theprogrammer67** [comment]
is it possible to start the service from the phone?

**Comment by rom1v** [comment]
> is it possible to start the service from the phone?

No.

**Comment by casper** [comment]
I have the same problem. I installed the APK manually by copying it over to the phone. 

It seems to be installed fine. This is the output of the dumpsys command:     
https://gist.github.com/casper/0a92e9a9b40458822cca855ce04f01bf

Shouldn't it be working this way too? When I run the START command the output is:

```
Broadcasting: Intent { act=com.genymobile.gnirehtet.START }
Broadcast completed: result=0
```

Does this mean it's running as it should? I still can't connect anywhere though.
Any way to debug this further to try and figure out the problem?

**Comment by rom1v** [comment]
> Does this mean it's running as it should?

It should open a dialog asking permission for VPN. Did you try this command when the screen was on?

**Comment by casper** [comment]
> It should open a dialog asking permission for VPN. Did you try this command when the screen was on?

Yes, with screen on. It never shows the VPN dialog, and it hasn't registered itself as a VPN in the Android settings either. Using the Java version on the computer btw, if that matters.

**Comment by rom1v** [comment]
Are there any relevant logs in the output of `adb logcat` when you start gnirehtet?

**Comment by casper** [comment]
Seems this might be relevant:

```
12-30 11:06:27.170 18777 18777 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
12-30 11:06:27.176 18777 18777 D AndroidRuntime: CheckJNI is OFF
12-30 11:06:27.216 18777 18777 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
12-30 11:06:27.253 18777 18777 E HAL     : Dawei load: module=/system/lib64/hw/memtrack.msm8937.so
12-30 11:06:27.257 18777 18777 I Radio-JNI: register_android_hardware_Radio DONE
12-30 11:06:27.291 18777 18777 D AndroidRuntime: Calling main entry com.android.commands.am.Am
12-30 11:06:27.321  1283  1329 D com.android.server.pm.PackageManagerServiceInjector: MIUILOG- permission denied android.permission.WRITE_SECURE_SETTINGS
12-30 11:06:27.321  1283  1329 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.genymobile.gnirehtet.START flg=0x10 cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver } from null (pid=18777, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS due to receiver com.genymobile.gnirehtet/.GnirehtetControlReceiver
12-30 11:06:27.323 18777 18777 D AndroidRuntime: Shutting down VM

```

**Comment by rom1v** [comment]
@casper 

> ```
> Permission Denial: broadcasting Intent { act=com.genymobile.gnirehtet.START flg=0x10 cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver } from null (pid=18777, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS due to receiver com.genymobile.gnirehtet/.GnirehtetControlReceiver
> ```

Then see [this issue](https://github.com/Genymobile/gnirehtet/issues/5#issuecomment-297045539).

**Comment by casper** [comment]
Thanks. I solved it through #40 by [editing the APK file](https://github.com/Genymobile/gnirehtet/issues/40#issuecomment-328369676) and removing the permission requirement. 

I did it this way because you cannot set elevated USB permissions on any new Xiaomi MIUI phones without requesting special permissions from Xiaomi.  At least I was not able to do it on my phone. Works fine now :) Thanks for your help.

**Comment by rom1v** [comment]
@theprogrammer67 does it also solve your problem?

**Comment by theprogrammer67** [comment]
I remove the android:permission="android.permission.WRITE_SECURE_SETTINGS" line from AndroidManifest.xml file. And now everything works on XIAOMI

**Comment by theprogrammer67** [comment]
Happy New Year! ))

**Comment by solokiran** [comment]
I have removed the said permission. here's the apk for v2.3 for XIAOMI

**Comment by dodyirawan85** [comment]
> I have removed the said permission. here's the apk for v2.3 for XIAOMI that I am using
> 
> [https://github.com/solokiran/hello-world/blob/master/gnirehtet2.apk](url)

Thank you, worked on color os 5 too

**Comment by anandumdas** [comment]
For Xiaomi devices you can enable `USB debugging(Security settings)` from developer options. It is there below the USB debugging option. No need to change the APK
