### ISSUE TITLE
Cannot relay: Address already in use (os error 98) on run

### ISSUE THREAD

**Issue by shillshocked** [Genymobile/gnirehtet#66]
./gnirehtet run
2017-12-08 15:22:41.502 INFO Main: Checking gnirehtet client...
2017-12-08 15:22:41.571 INFO Main: Starting relay server...
2017-12-08 15:22:41.571 INFO Main: Starting client...
thread 'main' panicked at 'Cannot relay: Address already in use (os error 98)', src/main.rs:179:16
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by rom1v** [comment]
You probably already have a relay server running. What is the result of:

    netstat -tapn | grep :31416

and:

    ps -ef | grep gnirehtet

?

**Comment by shillshocked** [comment]
You're right. Ran it in two clients... :P
