### ISSUE TITLE
tried this out today,  got an error ...

### ISSUE THREAD

**Issue by Antigonus** [Genymobile/gnirehtet#70]
Ubuntu 17.10 
plugged the Android phone in via USB

```
> sudo apt-get install android-tools-adb
...
downloaded gnirehtet-rust-linux64-v2.1.zi  via browser
sha256sum checks
> unzip gnirehtet-rust-linux64-v2.1.zip
> cd gnirehtet-rust-linux64/
> ./gnirehtet run
2017-12-20 11:15:25.332 INFO Main: Checking gnirehtet client...
2017-12-20 11:15:25.339 ERROR Main: Execution error: Command adb ["shell", "dumpsys", "package", "com.genymobile.gnirehtet"] returned with value 255
```

Ah so how can I make this work? 

------

I then downloaded the project, but got a gradle version error,  I suppose this is easy to solve?  perhaps I a different apt-get install command? 
```
> sudo apt-get install gradle
> gradle build
...
FAILURE: Build failed with an exception.

* Where:
Build file '/home/plato/tmp/gnirehtet-master/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
 > Minimum supported Gradle version is 3.3. Current version is 3.2.1. If using the gradle wrapper, try editing the distributionUrl in /home/plato/tmp/gnirehtet-master/gradle/wrapper/gradle-wrapper.properties to gradle-3.3-all.zip

```

**Comment by rom1v** [comment]
2017-12-20 11:15:25.339 ERROR Main: Execution error: Command adb ["shell", "dumpsys", "package", "com.genymobile.gnirehtet"] returned with value 255

Your device is probably not detected by `adb`. What is the result of:

    adb devices

?

**Comment by Antigonus** [comment]
Hello Romain

With the phone connected on the USB port.   The Linux kernel does find it,
as 'libmtp-1-2 appears in /dev, and the phone shows up in the file manager,
and I can see the phone memory there.  (where the heck is it mounted?)

Yes, you are right, adb does not see it:

> adb devices
List of devices attached

>

**Comment by Antigonus** [comment]
The phone is a Taiwan Mobile (TMZ ?)  Amazing X3s.  ... and I see that the
model matters here.  Apparently I need a device ID of some sort to tell adb
about it?

On Fri, Dec 22, 2017 at 8:45 PM, Thomas Lynch <thomas.walker.lynch@gmail.com

**Comment by rom1v** [comment]
If you install `adb` from the `android-tools-adb` package, you should get expected udev rules.

Otherwise, edit `/etc/udev/rules.d/51-android.rules` in order to authorize your device.

**Comment by Antigonus** [comment]
yes, and it worked!   Thanks!

**Comment by Bitik24** [comment]
Hiii. I have the same problem and this is the result when I type adb devices
!1fbf860.PNG)[sads](https://user-images.githubusercontent.com/65590512/82297066-b5ce2280-99e4-11ea-97c3-441b7

**Comment by Bitik24** [comment]
Hi. I have the same problem and this is what happens when I type adb devices.

![sads](https://user-images.githubusercontent.com/65590512/82297149-d26a5a80-99e4-11ea-829c-0d9f9b49e007.PNG)
