### ISSUE TITLE
connect / disconnect from client app

### ISSUE THREAD

**Issue by Xaviou18** [Genymobile/gnirehtet#75]
hi, first of all , thank you for your app which is just great !.
I wondered if there is a possibility  to connect/disconnect  client app from  the device itself , letting the server wait for a connection.
When the client is disconnected  TunnelServer: client #0 disconnected appears.
in issue #47 you said :

>Unfortunately, unplugging the USB cable kills the `adb reverse` tunnel.
>
>> So you don't need to restart desktop app in order to reconnect your device
>
> In fact, restarting the tunnel is sufficient:
>
>     adb reverse tcp:31416 tcp:31416

It seems to me not so obvious to type this command in another terminal, as the server is still running in the first opened one,  but it works fine .
Simply it would be great to do so from the client . Thank you again for this great job.

**Comment by rom1v** [comment]
> Simply it would be great to do so from the client.

Unfortunately, when the tunnel is broken, the client may not communicate to the server.

**Comment by Xaviou18** [comment]
Ok but wouldn't it be possible to send  :adb reverse tcp:31416 tcp:31416 command from the client to server through  OS  ( linux is my case)? 
Sorry if my question appears dumb .

**Comment by rom1v** [comment]
No, it's not possible for the client (this would require the tunnel to already be available).

Maybe the new `autostart`/`autorun` feature will solve your problem: https://github.com/Genymobile/gnirehtet/issues/47#issuecomment-363545799
