### ISSUE TITLE
pluging multiple devices 

### ISSUE THREAD

**Issue by Xaviou18** [Genymobile/gnirehtet#76]
Hi , 
If I want to use multiple device simultanuously , I have to Install the apk on each Android device:

./gnirehtet install [serial]

But How to find the serial number of the device ?
Thank you for your help

**Comment by rom1v** [comment]
> How to find the serial number of the device ?

    adb devices

**Comment by rom1v** [comment]
It would also make sens to implement something like `gnirehtet auto` which starts _gnirehtet_ whenever a device is connected. https://github.com/Genymobile/gnirehtet/issues/49

**Comment by Xaviou18** [comment]
great it works ! thx
