### ISSUE TITLE
gnirehtet relay in C/C++ language

### ISSUE THREAD

**Issue by Biswa96** [Genymobile/gnirehtet#78]
I'm trying to create your project in C++ just for learning. Ive some basic idea about socket and networking. I'm not so familiar with Java or Rust now. In the developer file, you've mentioned some library i.e. Java NIO and Rust mio. Is there any similar library in C/C++?

**Comment by rom1v** [comment]
> I'm trying to create your project in C++ just for learning.

:smile:

> Is there any similar library in C/C++?

In pure C, I think you can't avoid a platform dependent implementation (poll/epoll on Linux, iocp on Windows, kqueue on BSD/MacOS...).

In C++, there is [Boost.Asio](http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio.html).

**Comment by Biswa96** [comment]
Why is that asynchronous I/O feature needed? Can't I just open and close sockets to pass those network packets?
I've recently seen libpcap/Winpcap driver to manipulate raw packets (into osi layer2). Can't just use that?

**Comment by rom1v** [comment]
> Can't I just open and close sockets to pass those network packets?

You need to relay several connections at once, so you typically have several sockets open to different addresses on the Internet. If you use synchronous I/O (i.e. blocking calls) instead of asynchronous I/O, you'll need two threads per socket (for reading and writing).

> I've recently seen libpcap/Winpcap driver to manipulate raw packets (into osi layer2). Can't just use that?

To manipulate raw packets, you need to be _root_ (the main purpose of _gnirehtet_ is to provide reverse tethering without _root_ access). See https://github.com/vvviperrr/SimpleRT or https://github.com/google/vpn-reverse-tether.

**Comment by Biswa96** [comment]
The readme file of Google VPN said this 
>This method leverages VpnService API and does not require root access.

**Comment by rom1v** [comment]
It does not require root access *on the device*, but it requires root access on the computer.

**Comment by Biswa96** [comment]
Is there any alternative of tun/tap driver in Windows? Your mentioned projects relay from tun interface, I've tried those successfully.

**Comment by Biswa96** [comment]
As I'm new to this field I'll go with your provided repo. I want to start with a simple one then I'll caome back to your project.
Thanks for help... 😉 Closing....

**Comment by Biswa96** [comment]
But one issue is common between those and your project. They can't allow Google Play Store to install apps, though one can surf Google Play Store to see apps. 
Did you find any cause for this issue? I see many user posted this issue in this repo.

**Comment by rom1v** [comment]
> Did you find any cause for this issue?

A priori, it's a PlayStore bug. https://github.com/Genymobile/gnirehtet/issues/37#issuecomment-327212487

**Comment by Biswa96** [comment]
@rom1v Is it possible to use gnirehtet's VPN -- to capture packets like [Packet Capture](https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture) or to change DNS like [DNS Switch](https://play.google.com/store/apps/details?id=net.mypush.dnsswitch) without root. The later two apps also use VPN.

**Comment by rom1v** [comment]
@Biswa96 _gnirehtet_ (internally) does capture packets (and forward them to the relay server), and also configure a custom DNS (with the `-d` option).

But its purpose is not to capture/display packet content or change DNS on the device.

**Comment by Biswa96** [comment]
Is there any future plan with GUI?
