### ISSUE TITLE
Full Gnirehtet support

### ISSUE THREAD

**Issue by hankytanky** [Genymobile/gnirehtet#80]
Does anybody know of a Phone + Rom (maybe with a root solution) combination which is able to have a total functionality (maybe simulating a wifi or mobile connection????) using Gnirehtet?

This would be awesome to know!

Thank you guys!

**Comment by rom1v** [comment]
IIUC, by "total functionality" you talk about problems with Google Play? https://github.com/Genymobile/gnirehtet/issues/37

After 10 days without answer, I'm closing since this is not an issue.

**Comment by tango25001** [comment]
I think hankytanky is looking for a solution, where the reverse tethering is not done via VPN, but emulating a "wifi" connection.
so the phone thinks it is wifi connected while running only gnirehtet.

An advenced gnirehtet version, maybe requiring root, but emulating a wifi connection over usb tethering would be really awesome. 

I have the same problem, most of the apps work but wifi calling for example does not.

**Comment by adhammagdy** [comment]
True, I have the same problem.. so many apps check for mobile or wifi connection before even trying to connect.. so even though gnirehtet is working correctly, apps see the phone offline..
