### ISSUE TITLE
thread 'main' panicked at 'invalid key'

### ISSUE THREAD

**Issue by glush** [Genymobile/gnirehtet#93]
windows 10. gnirehtet-rust-win64-issue85.zip

Sometimes eventally. When IDLE.

2018-03-15 08:55:11.251 INFO TunnelServer: Client #0 disconnected
thread 'main' panicked at 'invalid key', /home/rom/.cargo/registry/src/github.com-1ecc6299db9ec823/slab-0.4.0/src/lib.rs:681:17
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust/src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust/src\libstd\sys_common\backtrace.rs:68
   2: std::panicking::rust_panic_with_hook
             at C:\projects\rust/src\libstd\panicking.rs:397
             at C:\projects\rust/src\libstd\panicking.rs:577
   3: std::panicking::begin_panic
   4: <slab::Slab<T>>::remove
   5: relaylib::relay::relay::Relay::run
   6: <gnirehtet::RunCommand as gnirehtet::Command>::execute
   7: gnirehtet::main
   8: std::rt::lang_start::{{closure}}
   9: main
  10: _tmainCRTStartup
  11: mainCRTStartup
  12: unit_addrs_search
Для продолжения нажмите любую клавишу . . .

**Comment by rom1v** [comment]
Take v2.2.1.

**Comment by glush** [comment]
Thnx.
