### ISSUE TITLE
Problems with Android 7.1.2

### ISSUE THREAD

**Issue by svladimirs** [Genymobile/gnirehtet#99]
Hello. At android 5.1 works perfect. But I can not start gnirehtet at android 7.1.2 (Redmi 4X). Help, please.
Android Composite ADB Interface 11.0.0.0 (28.08.14) installed (Win7x64).
adb.exe, AdbWinApi.dll and AdbWinUsbApi.dll exist in directory of gnirehtet.

2018-04-01 13:42:01.721 INFO Main: Starting relay server...
2018-04-01 13:42:01.721 INFO Relay: Relay server started
2018-04-01 13:42:01.721 INFO Main: Checking gnirehtet client...
2018-04-01 13:42:01.809 INFO Main: Installing gnirehtet client...
adb: failed to install gnirehtet.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
2018-04-01 13:42:07.054 ERROR Main: Cannot start on device 4d44d2aa7cf4: Command adb ["-s", "4d44d2aa7cf4", "install", "-r", "gnirehtet.apk"] returned with value 1

If I install apk manually:
2018-04-01 13:46:02.146 INFO Main: Starting relay server...
2018-04-01 13:46:02.146 INFO Main: Checking gnirehtet client...
2018-04-01 13:46:02.146 INFO Relay: Relay server started
2018-04-01 13:46:02.226 INFO Main: Starting client...
Broadcasting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetCon
trolReceiver }
Broadcast completed: result=0

apk not started and I do not get Connection request... Is problems in security options?

**Comment by rom1v** [comment]
How did you install the apk manually?

What if you uninstall it then:

    adb install gnirehtet.apk

?

Your device has probably options in developers settings to disable some additional restrictions specific to your ROM.

**Comment by svladimirs** [comment]
How did you install the apk manually? - in android from directory on SD card
D:\Distrib\gnirehtet-rust-win64>adb install gnirehtet.apk
adb: failed to install gnirehtet.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]

**Comment by lichao2018** [comment]
delete code in AndroidManifest.xml:

tools:replace="android:appComponentFactory"
android:appComponentFactory=""

it works.

**Comment by Sam217** [comment]
Hello, on MIUI v10.2 (xiaomi device) gnirehtet.apk is installed over adb, but the error is the same, no connection prompt and cmd ends here:
Broadcast completed: result=0

Tested on Xiaomi MiMix 2 and Xiaomi Redmi 4X/PRO.

However, on Android Oreo installed on my Xperia Z2 works as it should...
Any solution for MIUI?

**Comment by jaykit9723058632** [comment]
same problem in redmi note 5 cant access apk and fail to install apk by adb

**Comment by aqeebimtiaz** [comment]
> How did you install the apk manually?
> 
> What if you uninstall it then:
> 
> ```
> adb install gnirehtet.apk
> ```
> 
> ?
> 
> Your device has probably options in developers settings to disable some additional restrictions specific to your ROM.

I had an issue on Xiaomi Mi A1, this solved it!!!! Thanks!!!

**Comment by budisentosa** [comment]
@aqeebimtiaz 
pls share

**Comment by budisentosa** [comment]
never mind @aqeebimtiaz 
i got it
in my case, upgrade adb to latest version
